/* Complete excuses. One or two sentences. {meeting} is the only slot. */
var EXCUSES = (function (root) {
  "use strict";

  root.EXCUSES = {
    meetings: [
      { id: "standup", minutes: 15, label: { en: "standup", ja: "朝会", zh: "站会" } },
      { id: "allhands", minutes: 60, label: { en: "all-hands", ja: "全社会議", zh: "全员会" } },
      { id: "oneonone", minutes: 30, label: { en: "1:1", ja: "1on1", zh: "一对一" } },
      { id: "sync", minutes: 15, label: { en: "quick sync", ja: "クイックシンク", zh: "快速同步" } },
      { id: "client", minutes: 45, label: { en: "client call", ja: "クライアント会議", zh: "客户会" } },
    ],
    tones: ["plausible", "suspicious", "absurd"],
    audiences: ["any", "boss", "team", "client"],
    lines: {
      plausible: {
        en: [
          "The meeting before the {meeting} is still going. I'll read the notes when it actually ends.",
          "A hold I put on my own calendar is sitting on this hour. It will not move.",
          "Two invites want this hour, and I already answered the earlier one.",
          "If I leave the call I'm in, both conversations get worse.",
          "Something I promised to finish before this slot is still on the screen.",
          "I'm in the other building. By the time I arrive, the useful part will be over.",
          "My badge opens every door except the one for the {meeting}.",
          "This laptop is installing an update it described as quick. It was optimistic.",
          "The headset is in a room I can see and cannot enter.",
          "The agenda still says TBD, so I'm treating the {meeting} as done.",
          "Everything on the invite would get there sooner as a message.",
          "The {meeting} is marked optional. I'm taking the option.",
          "This slot was going to borrow time from lunch. Lunch is keeping it.",
          "A thread marked urgent opened a few minutes ago, and it believes itself.",
          "The review that started late has not heard that it should end.",
          "Transit is late. I can send the follow-up, not attend the hour.",
          "I stepped out for one document. The document became a corridor.",
          "The block before this one changed its name instead of ending.",
          "I can put the point in writing. I can't be in two rooms.",
          "The camera stopped this morning. A note will be clearer than a black tile.",
          "Audio from my side would be a guess. The {meeting} doesn't need one.",
          "I looked for a decision that needs me live. There isn't one.",
          "I'll be free when the earlier call admits it's over. That isn't a time on the clock.",
          "I'm on the way in, and the way in has the rest of this hour.",
          "I have to sign for something in this exact window. It will not wait.",
          "An earlier commitment is already on this slot. It got here first.",
          "Last time's notes cover this. I'll comment there.",
          "The hours on either side are full. This one didn't get a chair.",
          "The room changed. I'm still walking to the old one.",
          "The doc I said I'd read before we meet is still unread. The doc wins.",
          "This is the only gap I have to send the note I already owe.",
          "The {meeting} overlaps a call I can't drop. I'll take the outcome instead.",
          "I put a focus block here on purpose. It is doing the job.",
          "The earlier meeting has the only headset that works.",
          "I checked the calendar twice. The conflict is still the conflict.",
          "I can make the next one. This one belongs to the meeting before it.",
          "Someone asked for this hour first, and I already said yes.",
          "The train is between stations. The update can leave from here, and I can't.",
          "An appointment I can't move landed on the {meeting}.",
          "The prep isn't finished. I'd rather finish it than show up without it.",
          "I'm covering a desk through the top of the hour. The desk doesn't dial in.",
          "A meeting that was supposed to be short is still here at the start of the {meeting}.",
          "I can do this in writing. The live version doesn't have a job for me.",
          "My part is three lines. The thread fits them better than the room does.",
          "I already sent the update this meeting was going to collect.",
          "The overlap is as long as the {meeting}. There is no remainder.",
          "I'm in the wrong building for a room on this floor.",
          "The badge line downstairs is using up the part of me that arrives on time.",
          "A note I said I'd send first is still unsent. If I join, that note is late too.",
          "Another thread is due at the same time, and that one has a deadline.",
          "I'll read the transcript. The transcript is the version with an ending.",
          "The previous host is still sharing a screen, and I'm still on that calendar.",
          "A one-off I can't reschedule took the hour.",
          "Moving the {meeting} would only move the overlap. I'll take the notes.",
          "I'm on a pickup in this window. I'll read the decisions after.",
          "The invite has no owner and no outcome. I'll wait for the one that does.",
          "I can do the work, or I can attend the {meeting}. The work does not fit in the margin.",
          "A call with a stakeholder moved onto this slot and can't shift. I'll report back.",
          "I'm already late to the meeting I'm in. I won't be early to the next.",
          "The only laptop that's on is mid-update. I'll write when it allows it.",
          "This hour is tentative on one invite and firm on the other. The firm one wins.",
          "The overrun from the last meeting runs straight into the {meeting}.",
        ],
        ja: [
          "前の会議が伸びていて、{meeting}に役に立つ時刻では着けません。終わってから議事を読みます。",
          "自分で押さえた予定が、この時間に居座っています。動かせません。",
          "招待が二つ重なっていて、先に返事したほうを取ります。",
          "今抜けると、二つの話が両方とも中途半端になります。",
          "この前に終えると言った仕事が、まだ画面に残っています。",
          "別の建物にいます。着いたころには、必要な部分が終わっています。",
          "{meeting}の部屋だけ、入館証が通りません。",
          "パソコンが「すぐ終わる」更新の途中です。すぐではなさそうです。",
          "ヘッドセットは見えています。その部屋には入れません。",
          "議題が未定のままなので、{meeting}は済んだものとして扱います。",
          "招待に書いてあることは、チャットのほうが早く着きます。",
          "{meeting}は任意参加です。任意のほうを取ります。",
          "この時間を昼から借りる予定でした。昼が返してくれません。",
          "数分前に「急ぎ」の連絡が来て、相手は本気です。",
          "遅れて始まった確認が、終わるタイミングをまだ知りません。",
          "電車が遅れています。その場には出られず、あとで補います。",
          "資料を一枚取りに出たまま、廊下にいます。",
          "前の予定は終わっていません。件名だけ変わりました。",
          "文章なら出せます。二つの部屋にはいられません。",
          "カメラが今朝から映りません。黒い画面より、メモを送ります。",
          "こちらの音声は推測になります。{meeting}には要りません。",
          "その場に私が必要な決定を探しました。見当たりません。",
          "前の通話が終わったと認めたら、空きます。時刻ではありません。",
          "向かっている途中で、この一時間は道で終わりそうです。",
          "この時間にちょうど、外せない受け取りがあります。",
          "{meeting}より先に、動かせない予定が入っています。",
          "前回の議事で足ります。コメントはそちらに書きます。",
          "前後が埋まっています。この時間に座る場所がありません。",
          "会議室が変わりました。古い部屋のほうへまだ歩いています。",
          "会う前に読むと言った文書が、まだ読み終わっていません。文書が先です。",
          "返すと約束した文章に使えるのが、この時間だけです。",
          "{meeting}が、抜けられない通話と重なりました。結果だけ受け取ります。",
          "自分で入れた集中の予定が、ちゃんと仕事をしています。",
          "前の会議が、動くヘッドセットを一つ占有しています。",
          "カレンダーは二度確認しました。重なりは残っています。",
          "次なら出られます。今回は、前の会議が持っていきました。",
          "この時間は、先に引き受けたほうがあります。",
          "電車が駅と駅のあいだです。文章は送れても、人は送れません。",
          "動かせない約束が、{meeting}の上に落ちています。",
          "準備が終わっていません。中身のない出席より、準備を先にします。",
          "この時間は席を空けられない番です。席は会議に出ません。",
          "短いはずの前の会議が、{meeting}の開始まで残っています。",
          "文章で足ります。その場の私に、仕事がありません。",
          "私の分は三行です。部屋よりチャットが向いています。",
          "この場で集めようとしていた更新は、もう送りました。",
          "重なりが{meeting}と同じ長さです。残りがありません。",
          "会議室はこの階で、私は別の建物です。",
          "下の入館列が長く、時間どおりに着く分はそこで終わります。",
          "先に送ると言ったメモがまだです。出ると、メモも遅れます。",
          "同じ時間に、期限のある別件があります。そちらが先です。",
          "文字起こしを読みます。あちらには終わりがあります。",
          "前の画面共有が終わっていません。私もその予定の中です。",
          "動かせない単発が、この時間を取りました。",
          "{meeting}を動かすと、重なりが動くだけです。議事を受け取ります。",
          "この時間は送りです。決まったことだけ、あとで見ます。",
          "主催も、決めることもない招待です。ある版を待ちます。",
          "仕事はできます。{meeting}と同じ時間にやると、仕事が残りません。",
          "関係者との通話がこの枠に入って、先方は動かせません。戻って共有します。",
          "今いる会議にも遅れています。次には早く出られません。",
          "開いているパソコンが更新中です。終わったら書きます。",
          "片方は仮の予定で、もう片方は仮ではありません。仮でないほうが残ります。",
          "前の会議の延長が、そのまま{meeting}にかかっています。",
        ],
        zh: [
          "上一场还没散，这场{meeting}我赶不上有用的那段。散了再看纪要。",
          "我自己锁上的那段忙，压在这个点上。挪不走。",
          "两场都要这个小时，我已经回了先到的那份。",
          "现在退出来，两场都会停在半截。",
          "我说好会前做完的东西，还在屏幕上。",
          "我在另一栋。赶到的时候，有用的部分已经过去了。",
          "门禁卡唯独打不开这场{meeting}的门。",
          "电脑在装一个自称很快的更新。看起来并不快。",
          "耳机我看得见，房间我进不去。",
          "议程还是待定，这场{meeting}我当它开完了。",
          "邀请上这些事，发消息更快。",
          "这场{meeting}写的是自愿参加。我选自愿。",
          "这个点再开会，午饭就没了。午饭留下。",
          "几分钟前来了条标着紧急的消息，对方很认真。",
          "迟到开始的评审，还不知道自己该结束。",
          "车晚了。人到不了，会后我补。",
          "我出去拿一份材料，人还在走廊里。",
          "上一场没结束，只是换了个标题。",
          "写成文字我能交。两个房间我分不了身。",
          "摄像头从早上起就是黑的。与其给大家一个黑窗，不如写一张说明。",
          "我这边的声音只会是猜测。这场{meeting}不需要。",
          "我找了找有没有必须我在场的决定。没有。",
          "等上一通承认自己结束，我才有空。这不是一个钟点。",
          "我还在路上。这个小时大概会耗在路上。",
          "这个点我得签收一个东西，它不等。",
          "这场{meeting}之前，已经有一个不能动的安排。",
          "上次的纪要够用。我在那上面写。",
          "前后都排满了。这个点没有位子。",
          "会议室换了。我还在往旧的那间走。",
          "我答应会前看完的文档还没看完。文档优先。",
          "这个小时是我唯一能把欠的文字还上的空档。",
          "这场{meeting}和一通不能挂的电话撞了。我收结果。",
          "我自己排的那段专注，正在干活。",
          "上一场占着唯一能用的耳机。",
          "日历我看了两遍。冲突还在。",
          "下一场我能到。这一场被上一场拿走了。",
          "这个点我先答应了别人。",
          "车停在两站中间。文字能发出去，人不能。",
          "有个推不掉的安排，落在这场{meeting}上。",
          "准备还没做完。没准备的出席，不如把准备做完。",
          "这个点我得守着位子。位子自己不会去开会。",
          "上一场说好很短，一直短到这场{meeting}开始。",
          "写成文字就够。现场没有要我做的事。",
          "我的部分就三行，放消息里比放房间里合适。",
          "这场会想收的更新，我已经发出去了。",
          "重叠把这场{meeting}占满了。没有剩下的。",
          "会议室在这层，我在另一栋。",
          "楼下门禁那队人，把我准时的那部分用完了。",
          "说好先发的说明还没写。我要是去开会，说明也迟到。",
          "同一时间有件带着截止时间的事。那件在前。",
          "我看文字记录。文字记录有结尾。",
          "上一场的共享屏幕还没停。我也还在那场的时间里。",
          "一个不能改期的安排，把这个点拿走了。",
          "挪开这场{meeting}，重叠也跟着挪。我改收纪要。",
          "这个点我在接人。决定我事后看。",
          "邀请上没有主持，也没有要决定的事。我等有的那一版。",
          "活我能干。跟这场{meeting}挤在一起，活就没了。",
          "有通相关的电话挪到了这个点，对方不能改。我回头同步。",
          "我现在这场已经迟到了。下一场早不了。",
          "还能开的那台电脑正在更新。它允许了我就写。",
          "一边是待定，另一边不是。不是待定的那场留下。",
          "上一场的延长，延长进了这场{meeting}。",
        ],
      },
      suspicious: {
        en: [
          "My calendar double-booked me with myself. I'm in the other one.",
          "I'm already in a meeting about whether the {meeting} should happen.",
          "The invite lists two times. I stayed with the one I saw first.",
          "The previous meeting ended on the calendar and nowhere else.",
          "A five-minute overlap has been five minutes for a while now.",
          "I stopped for one hallway question. It formed a quorum.",
          "Both rooms believe I am in the other one.",
          "Someone accepted the {meeting} for me. They are busy, and so am I.",
          "The room number changed while I was walking to the old one.",
          "I'm badged into the building and not into the {meeting}.",
          "The agenda is the title, repeated. I'm treating that as the whole meeting.",
          "I've been to this meeting. Only the title is new.",
          "The only decision on the invite is whether to hold the {meeting}.",
          "The laptop is awake. The part that joins meetings is asleep.",
          "The headphones are still paired to last week.",
          "I would explain the conflict, but the explanation is booked too.",
          "The calendar settled this without calling a meeting. I'm following its example.",
          "I have been about to join since the invite was still on time.",
          "I can see the meeting room. The meeting room cannot see a reason to open.",
          "Most of the invite is optional. That already feels like an answer.",
          "Send the outcome. An outcome is the only thing I can attend twice.",
          "The loading spinner has perfect attendance. I don't.",
          "I looked through the invite for a verb. I found the name of a meeting.",
          "A copy of this hour is already in progress. I'm in that copy.",
          "The invite moved while I was reading it. I stayed with the old one.",
          "My microphone declined on my behalf.",
          "I'm waiting outside my own desk. The door has not agreed.",
          "The map and the building disagree. I'm with the hallway.",
          "Sound is working for everyone who isn't me.",
          "My remark is three words. It does not need a room.",
          "If I join, you get the version of me that is still on the other call.",
          "The earlier hold has the better claim. I didn't write the rule, but I'm keeping it.",
          "I nodded. The camera decided not to see it.",
          "I'll write the opinion I would have said into the notes.",
          "The other hold doesn't know this invite, and it was here first.",
          "Joining would add a second login to a meeting that already has me.",
          "This meeting needs someone who is only in this meeting.",
          "The update can attend. It says it is almost done.",
          "I refuse to be the frozen face in the corner.",
          "The message already contains the meeting. The meeting does not.",
          "I'm early for a room that isn't on this floor.",
          "Transit gave me a delay and called it a seat.",
          "I'll take the hallway version. It's the short one.",
          "Count me out of the room and in on the notes.",
          "The previous meeting is still introducing itself.",
          "I gave the overlap five more minutes. It accepted them.",
          "My location is approximate. My absence is exact.",
          "The laptop is in a meeting of its own.",
          "I can send a version that loads. This camera can't.",
          "Don't wait on a camera that is still showing this morning.",
          "The only place I still have audio is the thread, so I'll answer there.",
          "The {meeting} is mandatory in the air and optional on the invite. I'm outside.",
          "I was optional last time. I'm keeping the streak.",
          "The earlier block will not give up the chair.",
          "Both bookings have somewhere to be next.",
          "I'm still in the preamble of a meeting that forgot its title.",
          "Please send the sentence this hour was going to turn into.",
          "I'll take the content. I'm declining the gathering.",
          "I have one question, which is why this is live.",
          "I'll edit the doc. That is the {meeting}, without the {meeting}.",
          "If this can be a message, I'll meet you in the message.",
          "The chair is closer than I am, and it doesn't have to walk.",
          "I'm one restart away from being useful, and I'm not taking it.",
          "The other meeting can't find me either. You can start.",
        ],
        ja: [
          "カレンダーが、私を私と二重予約しました。もう一方にいます。",
          "{meeting}をやるかどうかの会議に、すでに入っています。",
          "招待の時刻が二つあります。先に見たほうに残ります。",
          "前の会議は、カレンダーの上でだけ終わりました。",
          "五分のはずの重なりが、五分のまま伸びています。",
          "廊下で質問を一つ受けたら、そのまま会議になりました。",
          "どちらの部屋も、私は向こうにいると思っています。",
          "誰かが私の代わりに{meeting}を承諾しました。その人も、私も、埋まっています。",
          "歩いているあいだに、会議室の番号が変わりました。",
          "建物には入れています。{meeting}には入れていません。",
          "議題が件名と同じ一文です。会議としては、そこで終わりです。",
          "同じ会議です。件名だけ新しいです。",
          "招待にある決定は、{meeting}を開くかどうかだけです。",
          "パソコンは起きています。会議に入る機能が寝ています。",
          "イヤホンの接続先が、先週のままです。",
          "理由は説明したいのですが、説明の時間も埋まっています。",
          "カレンダーは会議を開かずに決めました。そこは見習います。",
          "招待がまだ時間どおりだった頃から、入るところです。",
          "会議室は見えています。開ける気は、会議室のほうにありません。",
          "任意の人が多すぎます。それ自体が答えです。",
          "結果なら二箇所で受け取れます。出席は一箇所です。",
          "読み込み中の表示だけが、皆勤です。",
          "招待から動詞を探しました。会議の名前しかありません。",
          "この時間の複製がすでに始まっていて、私はそちらにいます。",
          "読んでいるあいだに招待が動きました。古いほうに残ります。",
          "マイクが、私の代わりに欠席しました。",
          "自席の前で待っています。ドアが納得していません。",
          "案内図と建物が食い違っています。私は廊下の側です。",
          "音が出ているのは、私以外です。",
          "発言は三語で済みます。部屋は要りません。",
          "入ると、まだ別の通話にいる私が出ます。",
          "先の予定のほうが、順番は上です。従います。",
          "うなずきました。カメラは見なかったことにしています。",
          "言うはずだった意見は、議事に書きます。",
          "もう一方の予定は、この招待を知りません。先にいたのは向こうです。",
          "入ると、すでに私がいる会議にログインがもう一つ増えます。",
          "この会議にだけいる人が、要ると思います。",
          "更新に出てもらいます。本人はもうすぐ終わると言っています。",
          "隅で止まった顔には、なりません。",
          "中身はチャットにすでにあります。会議のほうにはありません。",
          "この階にない部屋に、早く着きました。",
          "電車が、席の代わりに遅延を渡してきました。",
          "廊下で済む版を受け取ります。短いほうです。",
          "部屋にはいません。議事にはいます。",
          "前の会議が、まだ自己紹介をしています。",
          "重なりにあと五分だけ渡しました。受け取られました。",
          "いる場所はあいまいです。欠席のほうは正確です。",
          "パソコンが、自分の会議に出ています。",
          "読み込める文章なら出せます。このカメラは出せません。",
          "今朝の映像のままのカメラは、待たなくて大丈夫です。",
          "声が残っているのはチャットなので、そちらで答えます。",
          "{meeting}は空気の中だけ必須です。私は空気の外にいます。",
          "前回も任意でした。今回も任意で揃えます。",
          "先に入っている予定が、席を譲りません。",
          "どちらの予定にも、次が詰まっています。",
          "件名を忘れた会議の、前置きにまだいます。",
          "この一時間がなりたかった一文を、あとでください。",
          "中身は受け取ります。集まることだけ辞退します。",
          "質問は一つです。なぜこの場なのか、です。",
          "文書を直します。{meeting}は、その文書で足ります。",
          "メッセージで済む話なら、メッセージで会います。",
          "椅子のほうが近いです。歩かなくていいので、椅子が先です。",
          "再起動すれば役に立てる距離ですが、押しません。",
          "もう一方の会議も、私を見つけられていません。先にどうぞ。",
        ],
        zh: [
          "日历把我和我自己订在了同一个时间。我在另一场里。",
          "我已经在开一场会，议题是这场{meeting}开不开。",
          "邀请上有两个时间。我留在先看见的那个。",
          "上一场会只在日历上结束了。",
          "那个五分钟的重叠，五分钟了有一会儿。",
          "走廊里有人问了我一句，然后就凑成了一场会。",
          "两边的房间都以为我在另一边。",
          "有人替我接受了这场{meeting}。他没空，我也没空。",
          "我走向原来那间的时候，房间号变了。",
          "我刷进了大楼，没有刷进这场{meeting}。",
          "议程和标题是同一句话。作为一场会，到这儿就够了。",
          "还是那场会。新的只有标题。",
          "邀请上唯一要决定的，是这场{meeting}开不开。",
          "电脑醒着。负责开会的那一部分在睡。",
          "耳机还连着上周。",
          "我想解释，可解释的时间也被占了。",
          "日历没开会就做了决定。这一点我照做。",
          "从邀请还算准时的时候起，我就一直是即将加入。",
          "我看得见会议室。会议室看不见开门的理由。",
          "可选的人太多了。这本身就是个答案。",
          "结果我能收两次。人只能到一次。",
          "转圈是唯一全勤的。",
          "我在邀请里找动词。只找到一场会的名字。",
          "这个小时有一份副本已经开始了。我在那一份里。",
          "邀请在我读的时候挪了。我留在旧的那场。",
          "麦克风替我请了假。",
          "我在自己工位门口等。门还没同意。",
          "平面图和大楼意见不一致。我站走廊这边。",
          "除了我，别人的声音都是好的。",
          "我要说的就三个字。不需要房间。",
          "我要是进去，进去的是还在另一通电话里的我。",
          "先占住的那场顺序在前。我照这个来。",
          "我点了头。摄像头决定没看见。",
          "我本来会说的那句，写进纪要里。",
          "另一场并不知道这封邀请。它先到。",
          "我再进一次，一场已经有我的会会多一个登录。",
          "这场会需要一个只在这场会里的人。",
          "让更新去参加。它说自己马上好。",
          "我拒绝当角落里那张卡住的脸。",
          "内容已经在消息里。会里还没有。",
          "我提前到了一间不在这层的房间。",
          "交通工具没给座位，给了一段晚点。",
          "我收走廊版。那一版比较短。",
          "房间里没有我。纪要里有。",
          "上一场还在做自我介绍。",
          "我又给重叠五分钟。它收下了。",
          "人在哪儿说不清。人不在，倒是很清楚。",
          "电脑在开它自己的会。",
          "能打开的文字版我可以发。这个摄像头不行。",
          "还停在今天早上的摄像头，不用等。",
          "我还剩声音的地方是消息，所以我在那儿答。",
          "这场{meeting}只在气氛里是必须的。我在气氛外面。",
          "上次我就是可选的。这次继续。",
          "先占住的那场不让座。",
          "两场后面都还有事。",
          "我还在一场忘了标题的会的开场白里。",
          "请把这一小时本来会变成的那句话发我。",
          "内容我收。聚在一起我辞。",
          "我只有一个问题：为什么要现场。",
          "我来改文档。这场{meeting}，文档就够了。",
          "一条消息能说完的，我们就在消息里见。",
          "椅子比我近。它不用走路，所以椅子优先。",
          "我离有用只差一次重启，而我不会按。",
          "另一场会也找不到我。你们先开。",
        ],
      },
      absurd: {
        en: [
          "My calendar double-booked me with myself, and the other me already accepted. I'm in the other one.",
          "The {meeting} accepted itself. I was not consulted.",
          "A previous version of me is already on the invite. Their notes are better.",
          "This hour belongs to a recurring event called Do Not. It has never missed.",
          "I tried to decline. The decline is waiting for approval.",
          "The meeting before this one is still introducing the meeting before that.",
          "A short question from this morning appointed a chair and a note-taker.",
          "I would leave the previous meeting, but it hasn't admitted I'm here, so I can't exit.",
          "The {meeting} is in a room that exists only on the invite.",
          "My chair is attending. I was not on the delivery list.",
          "The elevator accepted the meeting and left the passengers behind.",
          "My microphone only speaks in calendar notifications.",
          "The laptop joined the {meeting} without me. It is doing fine.",
          "The camera will not cross the loading bar.",
          "The agenda is a link to the agenda, and the link is this {meeting}.",
          "I went to the pre-meeting. It was the pre-meeting for another pre-meeting.",
          "The {meeting} was there to keep the calendar from looking empty. The calendar looks fine.",
          "Every item says align. We are aligned, so the meeting can stay home.",
          "I brought a decision. The agenda told me to leave it outside.",
          "This meeting fits in one sentence. The sentence is no.",
          "I shortened the agenda, and the short version called in absent.",
          "Time is attending. I'm the optional one.",
          "The overlap contains another overlap. I'm in the inner one.",
          "I sent my regrets. The meeting replied with an agenda.",
          "A blank with my name will attend. It has opinions and no microphone.",
          "Count me present in the attachments.",
          "I'm sending the yes in advance. That's the only way I can attend.",
          "If I appear, that is the other me, and it doesn't get a vote.",
          "I'll haunt the document, not the call.",
          "A more presentable copy of me will write later. This one is fully booked.",
          "You will get the work. The work is not double-booked.",
          "Please remove the copy of me that can still see a clock.",
          "The meetings are nested too deep. I can't reach the exit.",
          "I can attend the recap of the recap. That's my assigned seat.",
          "Forward only the ending. I collect those.",
          "My status is blocked. The blocker is a meeting.",
          "Facilities registered me as furniture. Furniture doesn't speak live.",
          "I took the stairs between buildings and came out yesterday.",
          "My out-of-office reply is in a meeting. I am not at my desk.",
          "A third copy of me would need a chair we don't have.",
          "My bandwidth is attending a longer meeting.",
          "The laptop sent a decline. I am that decline.",
          "Technical support is me, and I closed the ticket.",
          "The laptop is meeting with the network. I was not invited.",
          "I support the outcome. I haven't been shown one, so this is early.",
          "Please mark me present in spirit and absent on the calendar.",
          "Please end on time, including the time before it starts.",
          "I'm in the document, making the headings match reality. The meeting can wait.",
          "If anyone finds an agenda item with a verb, call me.",
          "We can be aligned by not meeting. I'm free for that.",
          "I'll take the work. This invitation faces the other way.",
          "One sentence from me will contain more than the agenda does.",
          "Please take the hour back. The purpose and I will meet in writing.",
          "Let the chair represent me. It has never talked over anyone.",
          "I'll report once I get back to the correct week.",
          "If a muted chair joins, that's my delegate. Be polite to it.",
          "I'm there in intention. The rest of me is elsewhere.",
          "I'll attend as a dot on the map. The dot is on time.",
          "You hold the meeting. I'll hold the hallway.",
          "This meeting has not found a purpose. I'm closing it here.",
          "The direction is settled. The person is in another room.",
          "My tile has declined to enter the call.",
        ],
        ja: [
          "カレンダーが私を私と二重予約し、もう一人が承諾しました。そちらにいます。",
          "{meeting}が自分で出席を押しました。私は聞いていません。",
          "前の版の私が、すでに招待に入っています。議事はあちらのほうが上手です。",
          "この時間は「入るな」という定例です。一度も休んでいません。",
          "辞退を出したら、辞退のほうが承認待ちになりました。",
          "前の会議が、その前の会議をまだ紹介しています。",
          "今朝の短い質問が、議長と書記を決めてしまいました。",
          "前の会議を出たいのですが、在席を認められていないので退室できません。",
          "{meeting}の部屋は、招待状の中にしかありません。",
          "椅子は出席しています。配送先に私は入っていません。",
          "エレベーターは会議に乗り、人は見送りました。",
          "マイクが話すのは、予定の通知だけです。",
          "パソコンが私を置いて{meeting}に入りました。調子はよさそうです。",
          "カメラが、読み込みの線を越えるのを断っています。",
          "議題が議題へのリンクで、そのリンクがこの{meeting}です。",
          "事前の打ち合わせに出ました。それも、事前のための事前でした。",
          "{meeting}はカレンダーを空に見せないためのものです。カレンダーはもう平気です。",
          "議題が全部「認識合わせ」です。認識は合っているので、会は不要です。",
          "結論を持っていったら、外に置いてくるよう言われました。",
          "この会議は一文で足ります。その一文は、欠席です。",
          "議題を短くしたら、短くなったほうが欠席しました。",
          "時間のほうが出席しています。任意なのは私です。",
          "重なりの奥に、もう一つの重なりがあります。私はそこにいます。",
          "欠席を送ったら、議題が返ってきました。",
          "名前の入った空欄が出席します。意見はあり、マイクはありません。",
          "添付の中に、私はいます。",
          "賛成だけ先に出します。出席できる形は、それだけです。",
          "画面に出たら、それは別の私です。投票はできません。",
          "入るなら会議ではなく、文書のほうです。",
          "もう少し整った私が、あとで書きます。今の私は満席です。",
          "成果は渡します。成果は二重に入っていません。",
          "まだ時計を見ているほうの私は、招待から外してください。",
          "会議が何重にもなって、出口まで届きません。",
          "振り返りの振り返りなら出られます。そこが定位置です。",
          "終わりだけ転送してください。集めています。",
          "止まっています。止まっている理由が会議です。",
          "総務に備品として登録されました。備品はその場で話しません。",
          "棟と棟のあいだの階段を上がったら、日付が昨日でした。",
          "不在通知のほうが会議中です。本人は席にいません。",
          "三人目の私には、ない椅子が要ります。",
          "回線が、もっと長い会議に出ています。",
          "パソコンが欠席の連絡を出しました。その欠席が私です。",
          "問い合わせ先が私で、その問い合わせは断りました。",
          "端末とネットワークが会議中です。私は呼ばれていません。",
          "結果には賛成です。まだ見ていないので、フライングです。",
          "気持ちは出席、カレンダーは欠席、で記録してください。",
          "始まる前の時間も含めて、時間どおりに終わってください。",
          "文書の見出しを現実に直しています。会議はそのあとで足ります。",
          "動詞のある議題が見つかったら、呼んでください。",
          "会わないことで揃います。その時間は空いています。",
          "仕事は受けます。この招待とは向きが違います。",
          "私からの一文のほうが、議題より中身があります。",
          "この一時間はお返しください。目的とは文章で会います。",
          "椅子を代理にしてください。人の話を遮ったことがありません。",
          "正しい週に戻ったら、報告します。",
          "ミュートの椅子が入ったら、私の代理です。やさしくしてください。",
          "気持ちはそちらです。身体は別の場所です。",
          "地図の点として出席します。点は時間どおりです。",
          "会議はそちらで開いてください。廊下は私が持ちます。",
          "目的の見つかっていない会議は、ここで閉じます。",
          "方向は揃いました。人は別の部屋です。",
          "私の画面は、この通話に入りません。",
        ],
        zh: [
          "日历把我和我自己订重了。另一个我点了接受，我在那场里。",
          "这场{meeting}自己接受了自己。没有人问过我。",
          "邀请里坐着上一版的我。纪要比我写得好。",
          "这个小时属于一个叫「别来」的例会。它从没缺席。",
          "我点了拒绝。拒绝还在等批准。",
          "上一场会还在介绍它的上一场会。",
          "早上一个小问题，已经指定了主持和记录。",
          "我想退出上一场，可它还没承认我在，所以我退不出去。",
          "这场{meeting}的房间只写在邀请里。",
          "椅子在参会。快递单上没有我。",
          "电梯进了会，人被留在外面。",
          "麦克风只会念日历通知。",
          "电脑没带我进了这场{meeting}。它状态很好。",
          "摄像头拒绝越过那条加载线。",
          "议程是一个指向议程的链接。那个链接就是这场{meeting}。",
          "我参加了预备会。那场会也是预备会的预备。",
          "这场{meeting}是用来填日历的。日历已经满了。",
          "每一项都是对齐。已经对齐了，会可以不开。",
          "我带了结论来。议程让我把结论放在门外。",
          "这场会一句话就够。那句话是：不去。",
          "议程缩短之后，缩短版请假了。",
          "时间在参会。可选的是我。",
          "重叠里面还有一层重叠。我在里面。",
          "我发了不去，它回我一份议程。",
          "写着我名字的空位会出席。它有意见，没有麦。",
          "请把我算在附件里。",
          "赞成人先交了。能出席的样子只剩这个。",
          "如果我出现，那是另一个我，不能投票。",
          "我缠上的是文档，不是这通电话。",
          "比较能见人的那个我稍后写。现在这个已经排满。",
          "东西会交。东西没有被订重。",
          "请把还在看表的那个我移出邀请。",
          "会套着会，我够不着出口。",
          "复盘的复盘我可以参加。那是我的固定座位。",
          "请只转发结尾。我在收集这个。",
          "状态是堵住了。堵住的原因是一场会。",
          "行政把我登记成了办公用品。办公用品不当场发言。",
          "我走了两栋楼之间的楼梯，出来已经是昨天。",
          "自动回复在开会。本人不在工位。",
          "第三个我需要一把我们没有的椅子。",
          "带宽在参加一场更长的会。",
          "电脑发来了请假。那封请假就是我。",
          "技术支持是我，这张单我关了。",
          "电脑和网络在开会，没有叫我。",
          "结论我赞成。结论我还没看见，所以这是抢跑。",
          "请记成：人在，日历不在。",
          "请准时结束，包括它还没开始的那段。",
          "我在文档里把标题改成现实。会可以等一等。",
          "谁要是找到一条带动词的议程，叫我。",
          "不开会就算对齐了。那个时段我有空。",
          "事情我接。这封邀请和事情不是一个方向。",
          "我写的一句话，比议程有内容。",
          "这个小时请收回。目的我们在文字里见。",
          "请让椅子当代表。它没打断过任何人。",
          "等我回到正确的那一周，再汇报。",
          "如果一把静音的椅子进来，那是我的代表。请对它客气。",
          "人很想在。人其实在别处。",
          "我作为地图上的一个点出席。点很守时。",
          "会你们开。走廊我守着。",
          "这场还没找到目的的会，现在闭会。",
          "方向齐了。人不在这个房间。",
          "我的小窗不进这通电话。",
        ],
      },
    },
  };

  return root.EXCUSES;
})(typeof globalThis !== "undefined" ? globalThis : this);
