/* Complete excuses. One or two sentences. {meeting} is the only slot. */
var EXCUSES = (function (root) {
  "use strict";

  root.EXCUSES = {
    meetings: [
      { id: "standup", minutes: 15, label: { en: "standup", ja: "朝会", zh: "站会" } },
      { id: "allhands", minutes: 60, label: { en: "all-hands", ja: "全社会議", zh: "全员大会" } },
      { id: "oneonone", minutes: 30, label: { en: "1:1", ja: "1on1", zh: "1对1" } },
      { id: "sync", minutes: 15, label: { en: "quick sync", ja: "クイックシンク", zh: "临时对齐会" } },
      { id: "client", minutes: 45, label: { en: "client call", ja: "クライアント会議", zh: "客户会议" } },
    ],
    tones: ["plausible", "suspicious", "absurd"],
    audiences: ["any", "boss", "team", "client"],
    lines: {
      plausible: {
        en: [
          "The meeting before the {meeting} is still going. I'll read the notes when it actually ends.",
          "A hold I put on my own calendar is sitting on this hour. It will not move.",
          "Two invites want this hour, and I already answered the earlier one.",
          "If I leave the call I'm in, both conversations get worse.",
          "Something I promised to finish before this slot is still on the screen.",
          "I'm in the other building. By the time I arrive, the useful part will be over.",
          "My badge opens every door except the one for the {meeting}.",
          "This laptop is installing an update it described as quick. It was optimistic.",
          "The headset is in a room I can see and cannot enter.",
          "The agenda still says TBD, so I'm treating the {meeting} as done.",
          "Everything on the invite would get there sooner as a message.",
          "The {meeting} is marked optional. I'm taking the option.",
          "This slot was going to borrow time from lunch. Lunch is keeping it.",
          "A thread marked urgent opened a few minutes ago, and it believes itself.",
          "The review that started late has not heard that it should end.",
          "Transit is late. I can send the follow-up, not attend the hour.",
          "I stepped out for one document. The document became a corridor.",
          "The block before this one changed its name instead of ending.",
          "I can put the point in writing. I can't be in two rooms.",
          "The camera stopped this morning. A note will be clearer than a black tile.",
          "Audio from my side would be a guess. The {meeting} doesn't need one.",
          "I looked for a decision that needs me live. There isn't one.",
          "I'll be free when the earlier call admits it's over. That isn't a time on the clock.",
          "I'm on the way in, and the way in has the rest of this hour.",
          "I have to sign for something in this exact window. It will not wait.",
          "An earlier commitment is already on this slot. It got here first.",
          "Last time's notes cover this. I'll comment there.",
          "The hours on either side are full. This one didn't get a chair.",
          "The room changed. I'm still walking to the old one.",
          "The doc I said I'd read before we meet is still unread. The doc wins.",
          "This is the only gap I have to send the note I already owe.",
          "The {meeting} overlaps a call I can't drop. I'll take the outcome instead.",
          "I put a focus block here on purpose. It is doing the job.",
          "The earlier meeting has the only headset that works.",
          "I checked the calendar twice. The conflict is still the conflict.",
          "I can make the next one. This one belongs to the meeting before it.",
          "Someone asked for this hour first, and I already said yes.",
          "The train is between stations. The update can leave from here, and I can't.",
          "An appointment I can't move landed on the {meeting}.",
          "The prep isn't finished. I'd rather finish it than show up without it.",
          "I'm covering a desk through the top of the hour. The desk doesn't dial in.",
          "A meeting that was supposed to be short is still here at the start of the {meeting}.",
          "I can do this in writing. The live version doesn't have a job for me.",
          "My part is three lines. The thread fits them better than the room does.",
          "I already sent the update this meeting was going to collect.",
          "The overlap is as long as the {meeting}. There is no remainder.",
          "I'm in the wrong building for a room on this floor.",
          "The badge line downstairs is using up the part of me that arrives on time.",
          "A note I said I'd send first is still unsent. If I join, that note is late too.",
          "Another thread is due at the same time, and that one has a deadline.",
          "I'll read the transcript. The transcript is the version with an ending.",
          "The previous host is still sharing a screen, and I'm still on that calendar.",
          "A one-off I can't reschedule took the hour.",
          "Moving the {meeting} would only move the overlap. I'll take the notes.",
          "I'm on a pickup in this window. I'll read the decisions after.",
          "The invite has no owner and no outcome. I'll wait for the one that does.",
          "I can do the work, or I can attend the {meeting}. The work does not fit in the margin.",
          "A call with a stakeholder moved onto this slot and can't shift. I'll report back.",
          "I'm already late to the meeting I'm in. I won't be early to the next.",
          "The only laptop that's on is mid-update. I'll write when it allows it.",
          "This hour is tentative on one invite and firm on the other. The firm one wins.",
          "The overrun from the last meeting runs straight into the {meeting}.",
        ],
        ja: [
          "前の会議が伸びていて、{meeting}に役に立つ時刻では着けません。終わってから議事を読みます。",
          "自分で押さえた予定が、この時間に居座っています。動かせません。",
          "招待が二つ重なっていて、先に返事したほうを取ります。",
          "今抜けると、二つの話が両方とも中途半端になります。",
          "この前に終えると言った仕事が、まだ画面に残っています。",
          "別の建物にいます。着いたころには、必要な部分が終わっています。",
          "{meeting}の部屋だけ、入館証が通りません。",
          "パソコンが「すぐ終わる」更新の途中です。すぐではなさそうです。",
          "ヘッドセットは見えています。その部屋には入れません。",
          "議題が未定のままなので、{meeting}は済んだものとして扱います。",
          "招待に書いてあることは、チャットのほうが早く着きます。",
          "{meeting}は任意参加です。任意のほうを取ります。",
          "この時間を昼から借りる予定でした。昼が返してくれません。",
          "数分前に「急ぎ」の連絡が来て、相手は本気です。",
          "遅れて始まった確認が、終わるタイミングをまだ知りません。",
          "電車が遅れています。その場には出られず、あとで補います。",
          "資料を一枚取りに出たまま、廊下にいます。",
          "前の予定は終わっていません。件名だけ変わりました。",
          "文章なら出せます。二つの部屋にはいられません。",
          "カメラが今朝から映りません。黒い画面より、メモを送ります。",
          "こちらの音声は推測になります。{meeting}には要りません。",
          "その場に私が必要な決定を探しました。見当たりません。",
          "前の通話が終わったと認めたら、空きます。時刻ではありません。",
          "向かっている途中で、この一時間は道で終わりそうです。",
          "この時間にちょうど、外せない受け取りがあります。",
          "{meeting}より先に、動かせない予定が入っています。",
          "前回の議事で足ります。コメントはそちらに書きます。",
          "前後が埋まっています。この時間に座る場所がありません。",
          "会議室が変わりました。古い部屋のほうへまだ歩いています。",
          "会う前に読むと言った文書が、まだ読み終わっていません。文書が先です。",
          "返すと約束した文章に使えるのが、この時間だけです。",
          "{meeting}が、抜けられない通話と重なりました。結果だけ受け取ります。",
          "自分で入れた集中の予定が、ちゃんと仕事をしています。",
          "前の会議が、動くヘッドセットを一つ占有しています。",
          "カレンダーは二度確認しました。重なりは残っています。",
          "次なら出られます。今回は、前の会議が持っていきました。",
          "この時間は、先に引き受けたほうがあります。",
          "電車が駅と駅のあいだです。文章は送れても、人は送れません。",
          "動かせない約束が、{meeting}の上に落ちています。",
          "準備が終わっていません。中身のない出席より、準備を先にします。",
          "この時間は席を空けられない番です。席は会議に出ません。",
          "短いはずの前の会議が、{meeting}の開始まで残っています。",
          "文章で足ります。その場の私に、仕事がありません。",
          "私の分は三行です。部屋よりチャットが向いています。",
          "この場で集めようとしていた更新は、もう送りました。",
          "重なりが{meeting}と同じ長さです。残りがありません。",
          "会議室はこの階で、私は別の建物です。",
          "下の入館列が長く、時間どおりに着く分はそこで終わります。",
          "先に送ると言ったメモがまだです。出ると、メモも遅れます。",
          "同じ時間に、期限のある別件があります。そちらが先です。",
          "文字起こしを読みます。あちらには終わりがあります。",
          "前の画面共有が終わっていません。私もその予定の中です。",
          "動かせない単発が、この時間を取りました。",
          "{meeting}を動かすと、重なりが動くだけです。議事を受け取ります。",
          "この時間は送りです。決まったことだけ、あとで見ます。",
          "主催も、決めることもない招待です。ある版を待ちます。",
          "仕事はできます。{meeting}と同じ時間にやると、仕事が残りません。",
          "関係者との通話がこの枠に入って、先方は動かせません。戻って共有します。",
          "今いる会議にも遅れています。次には早く出られません。",
          "開いているパソコンが更新中です。終わったら書きます。",
          "片方は仮の予定で、もう片方は仮ではありません。仮でないほうが残ります。",
          "前の会議の延長が、そのまま{meeting}にかかっています。",
        ],
        zh: [
          "上一个会拖堂了，还没散，这个{meeting}我赶不上了。",
          "刚被拉进一个线上问题排查，暂时走不开。",
          "客户临时要一版材料，下班前必须交。",
          "这个时间我之前约了别的会，撞了。",
          "电脑在强制更新，进度条才走到一半。",
          "我在外面跑客户，路上信号不太好。",
          "孩子学校临时叫家长，我得过去一趟。",
          "今天有点发烧，请了半天假在家休息。",
          "地铁故障停在半路了，赶不回来。",
          "耳机坏了，麦克风也没声音，进会也说不了话。",
          "手上有个版本今天必须上线，我在盯发布。",
          "这个议题我上周已经在群里同步过了，结论没变。",
          "今天去医院复查，号是早就挂好的，改不了。",
          "我在另一栋楼的会议室，走过去要十几分钟。",
          "领导临时叫我过去对个事。",
          "月底了，财务在催我对单子。",
          "今天在外地出差，这个点在高铁上。",
          "有个快递必须本人签收，我在楼下等着。",
          "网断了，手机热点也连不上。",
          "这个会我不是必须参加的，我看纪要就行。",
          "我那部分直接写成文档发群里，大家有问题在评论里提。",
          "下午约了候选人面试，时间撞了。",
          "家里水管漏了，物业师傅马上上门。",
          "刚接到一个紧急工单，在处理。",
          "我在陪客户吃饭，不方便走开。",
          "这个时间段约了供应商对账。",
          "今天调休，人不在公司。",
          "明早要交的方案还差一半，我先赶这个。",
          "今天限号，打不到车，还在路上。",
          "这个{meeting}和我的年假撞了，假上周就批了。",
          "在开另一个项目的评审，暂时出不来。",
          "线上有个报警，我得先看一下。",
          "这周在支援隔壁组，他们上午都排满了。",
          "牙疼，约了下午看牙医。",
          "老家来人了，我去车站接一下。",
          "这个议题我参与得不多，有需要我配合的会后跟我说。",
          "在给新同事做交接，约好的时间不好改。",
          "我在客户现场做部署，一时走不开。",
          "今天上午体检，还在空腹排队。",
          "这个点有个培训考试，缺考还得补。",
          "上午请假去办证件，窗口排队还没轮到我。",
          "领导让我今天把预算表做完，我先弄这个。",
          "日历上这个时间我早就标了忙，可能大家没看到。",
          "我在飞机上，落地再看消息。",
          "吃坏肚子了，今天状态不行，请半天假。",
          "有份合同今天必须盖章寄出，我在跑流程。",
          "今晚系统切换，我得在机房守着。",
          "这周我值班，这个点正好轮到我。",
          "会议软件一直登不上，提示账号异常。",
          "和财务约好了核对报销，错过今天就得等下个月。",
          "我这边网太卡，进会也是一卡一卡的，不如会后看纪要。",
          "上次会的待办我还没做完，进会也没有新进展可讲。",
          "刚收到客户投诉，得先打电话安抚一下。",
          "家里老人不舒服，我陪着去趟医院。",
          "今天搬工位，电脑还在箱子里没接上。",
          "在做季度复盘材料，明天一早要给领导看。",
          "这个时间我在开车，进会也只能听，不方便说话。",
          "小区停电检修，家里网断了。",
          "在和法务对合同条款，对完才能走。",
          "手机快没电了，充电器落在公司了。",
          "周报系统中午十二点就锁了，我得先交。",
          "这个{meeting}和一个改不了的外部会议撞了，结论麻烦会后发我一下。",
        ],
      },
      suspicious: {
        en: [
          "My calendar double-booked me with myself. I'm in the other one.",
          "I'm already in a meeting about whether the {meeting} should happen.",
          "The invite lists two times. I stayed with the one I saw first.",
          "The previous meeting ended on the calendar and nowhere else.",
          "A five-minute overlap has been five minutes for a while now.",
          "I stopped for one hallway question. It formed a quorum.",
          "Both rooms believe I am in the other one.",
          "Someone accepted the {meeting} for me. They are busy, and so am I.",
          "The room number changed while I was walking to the old one.",
          "I'm badged into the building and not into the {meeting}.",
          "The agenda is the title, repeated. I'm treating that as the whole meeting.",
          "I've been to this meeting. Only the title is new.",
          "The only decision on the invite is whether to hold the {meeting}.",
          "The laptop is awake. The part that joins meetings is asleep.",
          "The headphones are still paired to last week.",
          "I would explain the conflict, but the explanation is booked too.",
          "The calendar settled this without calling a meeting. I'm following its example.",
          "I have been about to join since the invite was still on time.",
          "I can see the meeting room. The meeting room cannot see a reason to open.",
          "Most of the invite is optional. That already feels like an answer.",
          "Send the outcome. An outcome is the only thing I can attend twice.",
          "The loading spinner has perfect attendance. I don't.",
          "I looked through the invite for a verb. I found the name of a meeting.",
          "A copy of this hour is already in progress. I'm in that copy.",
          "The invite moved while I was reading it. I stayed with the old one.",
          "My microphone declined on my behalf.",
          "I'm waiting outside my own desk. The door has not agreed.",
          "The map and the building disagree. I'm with the hallway.",
          "Sound is working for everyone who isn't me.",
          "My remark is three words. It does not need a room.",
          "If I join, you get the version of me that is still on the other call.",
          "The earlier hold has the better claim. I didn't write the rule, but I'm keeping it.",
          "I nodded. The camera decided not to see it.",
          "I'll write the opinion I would have said into the notes.",
          "The other hold doesn't know this invite, and it was here first.",
          "Joining would add a second login to a meeting that already has me.",
          "This meeting needs someone who is only in this meeting.",
          "The update can attend. It says it is almost done.",
          "I refuse to be the frozen face in the corner.",
          "The message already contains the meeting. The meeting does not.",
          "I'm early for a room that isn't on this floor.",
          "Transit gave me a delay and called it a seat.",
          "I'll take the hallway version. It's the short one.",
          "Count me out of the room and in on the notes.",
          "The previous meeting is still introducing itself.",
          "I gave the overlap five more minutes. It accepted them.",
          "My location is approximate. My absence is exact.",
          "The laptop is in a meeting of its own.",
          "I can send a version that loads. This camera can't.",
          "Don't wait on a camera that is still showing this morning.",
          "The only place I still have audio is the thread, so I'll answer there.",
          "The {meeting} is mandatory in the air and optional on the invite. I'm outside.",
          "I was optional last time. I'm keeping the streak.",
          "The earlier block will not give up the chair.",
          "Both bookings have somewhere to be next.",
          "I'm still in the preamble of a meeting that forgot its title.",
          "Please send the sentence this hour was going to turn into.",
          "I'll take the content. I'm declining the gathering.",
          "I have one question, which is why this is live.",
          "I'll edit the doc. That is the {meeting}, without the {meeting}.",
          "If this can be a message, I'll meet you in the message.",
          "The chair is closer than I am, and it doesn't have to walk.",
          "I'm one restart away from being useful, and I'm not taking it.",
          "The other meeting can't find me either. You can start.",
        ],
        ja: [
          "カレンダーが、私を私と二重予約しました。もう一方にいます。",
          "{meeting}をやるかどうかの会議に、すでに入っています。",
          "招待の時刻が二つあります。先に見たほうに残ります。",
          "前の会議は、カレンダーの上でだけ終わりました。",
          "五分のはずの重なりが、五分のまま伸びています。",
          "廊下で質問を一つ受けたら、そのまま会議になりました。",
          "どちらの部屋も、私は向こうにいると思っています。",
          "誰かが私の代わりに{meeting}を承諾しました。その人も、私も、埋まっています。",
          "歩いているあいだに、会議室の番号が変わりました。",
          "建物には入れています。{meeting}には入れていません。",
          "議題が件名と同じ一文です。会議としては、そこで終わりです。",
          "同じ会議です。件名だけ新しいです。",
          "招待にある決定は、{meeting}を開くかどうかだけです。",
          "パソコンは起きています。会議に入る機能が寝ています。",
          "イヤホンの接続先が、先週のままです。",
          "理由は説明したいのですが、説明の時間も埋まっています。",
          "カレンダーは会議を開かずに決めました。そこは見習います。",
          "招待がまだ時間どおりだった頃から、入るところです。",
          "会議室は見えています。開ける気は、会議室のほうにありません。",
          "任意の人が多すぎます。それ自体が答えです。",
          "結果なら二箇所で受け取れます。出席は一箇所です。",
          "読み込み中の表示だけが、皆勤です。",
          "招待から動詞を探しました。会議の名前しかありません。",
          "この時間の複製がすでに始まっていて、私はそちらにいます。",
          "読んでいるあいだに招待が動きました。古いほうに残ります。",
          "マイクが、私の代わりに欠席しました。",
          "自席の前で待っています。ドアが納得していません。",
          "案内図と建物が食い違っています。私は廊下の側です。",
          "音が出ているのは、私以外です。",
          "発言は三語で済みます。部屋は要りません。",
          "入ると、まだ別の通話にいる私が出ます。",
          "先の予定のほうが、順番は上です。従います。",
          "うなずきました。カメラは見なかったことにしています。",
          "言うはずだった意見は、議事に書きます。",
          "もう一方の予定は、この招待を知りません。先にいたのは向こうです。",
          "入ると、すでに私がいる会議にログインがもう一つ増えます。",
          "この会議にだけいる人が、要ると思います。",
          "更新に出てもらいます。本人はもうすぐ終わると言っています。",
          "隅で止まった顔には、なりません。",
          "中身はチャットにすでにあります。会議のほうにはありません。",
          "この階にない部屋に、早く着きました。",
          "電車が、席の代わりに遅延を渡してきました。",
          "廊下で済む版を受け取ります。短いほうです。",
          "部屋にはいません。議事にはいます。",
          "前の会議が、まだ自己紹介をしています。",
          "重なりにあと五分だけ渡しました。受け取られました。",
          "いる場所はあいまいです。欠席のほうは正確です。",
          "パソコンが、自分の会議に出ています。",
          "読み込める文章なら出せます。このカメラは出せません。",
          "今朝の映像のままのカメラは、待たなくて大丈夫です。",
          "声が残っているのはチャットなので、そちらで答えます。",
          "{meeting}は空気の中だけ必須です。私は空気の外にいます。",
          "前回も任意でした。今回も任意で揃えます。",
          "先に入っている予定が、席を譲りません。",
          "どちらの予定にも、次が詰まっています。",
          "件名を忘れた会議の、前置きにまだいます。",
          "この一時間がなりたかった一文を、あとでください。",
          "中身は受け取ります。集まることだけ辞退します。",
          "質問は一つです。なぜこの場なのか、です。",
          "文書を直します。{meeting}は、その文書で足ります。",
          "メッセージで済む話なら、メッセージで会います。",
          "椅子のほうが近いです。歩かなくていいので、椅子が先です。",
          "再起動すれば役に立てる距離ですが、押しません。",
          "もう一方の会議も、私を見つけられていません。先にどうぞ。",
        ],
        zh: [
          "网突然不太好，只有我这台电脑不好。",
          "进会一直在转圈，已经转了半小时了。",
          "有点事，具体什么事，等我想好了再说。",
          "会议链接点不开，我就没再点了。",
          "我以为这个{meeting}是下周的，今天已经约了别的。",
          "家里WiFi坏了，只有外卖软件还能用。",
          "我在楼下取快递，快递有点多，大概要一个小时。",
          "我日历上今天没有会，我选择相信日历。",
          "刚开完一个会，嗓子说哑了，得歇一歇。",
          "电脑在更新，这已经是今天第三次了。",
          "我在外面，旁边太吵了，听不清，就先不进了。",
          "突然想起一件很重要的事，正在想是什么事。",
          "我已经在路上了，往家的方向。",
          "腰闪了，坐着疼，站着疼，开会更疼。",
          "会议邀请掉进了垃圾邮件，我也是刚翻到。",
          "手上有个紧急需求，客户说很急，具体多急他也没说。",
          "摄像头坏了，麦克风也坏了，刚好都是今天。",
          "我在开另一个会，那个会也是我自己约的。",
          "刚吃完午饭，大脑还在加载。",
          "这个{meeting}的议题，我已经在心里对齐过了。",
          "在等一个很重要的电话，它还没打来，但随时会打来。",
          "停电了，只停了我家这一户。",
          "蓝牙耳机连到了邻居家的电视上，正在处理。",
          "有个文档要赶，文档名字还没想好。",
          "在体检，排的人有点多，可能要排到下班。",
          "猫把键盘踩坏了，现在只剩退出键能用。",
          "我钉钉一直显示离线，我自己也觉得我离线了。",
          "今天水逆，不宜开会。",
          "在带新人熟悉业务，主要是熟悉食堂。",
          "车停的地方要被贴条了，我下去挪个车，可能挪得有点远。",
          "刚才在电梯里断了信号，现在还在电梯里。",
          "这周在调作息，按计划这个点我在睡觉。",
          "外卖送错小区了，我得去隔壁小区拿。",
          "我准备得很充分，都准备在脑子里了，还需要点时间整理。",
          "这个会上次参加过了，我感觉大家说的应该差不多。",
          "刚跟领导汇报完，领导说我可以不用来了。我理解是这个意思。",
          "投影我连不上，所以人也决定先不连了。",
          "家里来了修空调的师傅，我得在旁边看着。已经看了很久了。",
          "在高铁上，这一路隧道有点多，全程都是隧道。",
          "今天穿的衣服不太适合开摄像头。",
          "在排查一个bug，bug说再给它一个小时。",
          "手上有件急事，急的程度大概跟这个会差不多。",
          "被拉进一个群，群里正在吵架，我得在场。",
          "电脑没电了，充电器被同事借走了，同事今天休假。",
          "闹钟设成了下午，刚醒。",
          "外卖骑手说三分钟到，已经说了四十分钟了。",
          "在给领导写一份很重要的材料，领导还不知道这件事。",
          "这个{meeting}的链接我点了，跳出来的是去年的会。",
          "我在一个没信号的地方，这条消息是排队发出来的。",
          "空调太冷了，我在楼下晒太阳回温。",
          "打印机卡纸了，我也卡住了。",
          "我今天上午的状态是“请勿打扰”，我得尊重它。",
          "下午有个面试。是我面别人，应该是。",
          "在核对数据，数据有点多，可能要核到会议结束。",
          "牙医说今天有空位，我牙还没疼，但机会难得。",
          "在帮行政搬水，一桶接一桶。",
          "我已经在会议室了，但好像不是这间。",
          "我妈突然打视频过来，挂了她会问我是不是在忙。",
          "楼下有个快递必须本人去拿，而且必须是现在。",
          "在开车，导航让我一直往前开。",
          "这个会跟我关系不大，我是这么感觉的。",
          "刚给自己倒了杯咖啡，等它凉了再说。",
        ],
      },
      absurd: {
        en: [
          "My calendar double-booked me with myself, and the other me already accepted. I'm in the other one.",
          "The {meeting} accepted itself. I was not consulted.",
          "A previous version of me is already on the invite. Their notes are better.",
          "This hour belongs to a recurring event called Do Not. It has never missed.",
          "I tried to decline. The decline is waiting for approval.",
          "The meeting before this one is still introducing the meeting before that.",
          "A short question from this morning appointed a chair and a note-taker.",
          "I would leave the previous meeting, but it hasn't admitted I'm here, so I can't exit.",
          "The {meeting} is in a room that exists only on the invite.",
          "My chair is attending. I was not on the delivery list.",
          "The elevator accepted the meeting and left the passengers behind.",
          "My microphone only speaks in calendar notifications.",
          "The laptop joined the {meeting} without me. It is doing fine.",
          "The camera will not cross the loading bar.",
          "The agenda is a link to the agenda, and the link is this {meeting}.",
          "I went to the pre-meeting. It was the pre-meeting for another pre-meeting.",
          "The {meeting} was there to keep the calendar from looking empty. The calendar looks fine.",
          "Every item says align. We are aligned, so the meeting can stay home.",
          "I brought a decision. The agenda told me to leave it outside.",
          "This meeting fits in one sentence. The sentence is no.",
          "I shortened the agenda, and the short version called in absent.",
          "Time is attending. I'm the optional one.",
          "The overlap contains another overlap. I'm in the inner one.",
          "I sent my regrets. The meeting replied with an agenda.",
          "A blank with my name will attend. It has opinions and no microphone.",
          "Count me present in the attachments.",
          "I'm sending the yes in advance. That's the only way I can attend.",
          "If I appear, that is the other me, and it doesn't get a vote.",
          "I'll haunt the document, not the call.",
          "A more presentable copy of me will write later. This one is fully booked.",
          "You will get the work. The work is not double-booked.",
          "Please remove the copy of me that can still see a clock.",
          "The meetings are nested too deep. I can't reach the exit.",
          "I can attend the recap of the recap. That's my assigned seat.",
          "Forward only the ending. I collect those.",
          "My status is blocked. The blocker is a meeting.",
          "Facilities registered me as furniture. Furniture doesn't speak live.",
          "I took the stairs between buildings and came out yesterday.",
          "My out-of-office reply is in a meeting. I am not at my desk.",
          "A third copy of me would need a chair we don't have.",
          "My bandwidth is attending a longer meeting.",
          "The laptop sent a decline. I am that decline.",
          "Technical support is me, and I closed the ticket.",
          "The laptop is meeting with the network. I was not invited.",
          "I support the outcome. I haven't been shown one, so this is early.",
          "Please mark me present in spirit and absent on the calendar.",
          "Please end on time, including the time before it starts.",
          "I'm in the document, making the headings match reality. The meeting can wait.",
          "If anyone finds an agenda item with a verb, call me.",
          "We can be aligned by not meeting. I'm free for that.",
          "I'll take the work. This invitation faces the other way.",
          "One sentence from me will contain more than the agenda does.",
          "Please take the hour back. The purpose and I will meet in writing.",
          "Let the chair represent me. It has never talked over anyone.",
          "I'll report once I get back to the correct week.",
          "If a muted chair joins, that's my delegate. Be polite to it.",
          "I'm there in intention. The rest of me is elsewhere.",
          "I'll attend as a dot on the map. The dot is on time.",
          "You hold the meeting. I'll hold the hallway.",
          "This meeting has not found a purpose. I'm closing it here.",
          "The direction is settled. The person is in another room.",
          "My tile has declined to enter the call.",
        ],
        ja: [
          "カレンダーが私を私と二重予約し、もう一人が承諾しました。そちらにいます。",
          "{meeting}が自分で出席を押しました。私は聞いていません。",
          "前の版の私が、すでに招待に入っています。議事はあちらのほうが上手です。",
          "この時間は「入るな」という定例です。一度も休んでいません。",
          "辞退を出したら、辞退のほうが承認待ちになりました。",
          "前の会議が、その前の会議をまだ紹介しています。",
          "今朝の短い質問が、議長と書記を決めてしまいました。",
          "前の会議を出たいのですが、在席を認められていないので退室できません。",
          "{meeting}の部屋は、招待状の中にしかありません。",
          "椅子は出席しています。配送先に私は入っていません。",
          "エレベーターは会議に乗り、人は見送りました。",
          "マイクが話すのは、予定の通知だけです。",
          "パソコンが私を置いて{meeting}に入りました。調子はよさそうです。",
          "カメラが、読み込みの線を越えるのを断っています。",
          "議題が議題へのリンクで、そのリンクがこの{meeting}です。",
          "事前の打ち合わせに出ました。それも、事前のための事前でした。",
          "{meeting}はカレンダーを空に見せないためのものです。カレンダーはもう平気です。",
          "議題が全部「認識合わせ」です。認識は合っているので、会は不要です。",
          "結論を持っていったら、外に置いてくるよう言われました。",
          "この会議は一文で足ります。その一文は、欠席です。",
          "議題を短くしたら、短くなったほうが欠席しました。",
          "時間のほうが出席しています。任意なのは私です。",
          "重なりの奥に、もう一つの重なりがあります。私はそこにいます。",
          "欠席を送ったら、議題が返ってきました。",
          "名前の入った空欄が出席します。意見はあり、マイクはありません。",
          "添付の中に、私はいます。",
          "賛成だけ先に出します。出席できる形は、それだけです。",
          "画面に出たら、それは別の私です。投票はできません。",
          "入るなら会議ではなく、文書のほうです。",
          "もう少し整った私が、あとで書きます。今の私は満席です。",
          "成果は渡します。成果は二重に入っていません。",
          "まだ時計を見ているほうの私は、招待から外してください。",
          "会議が何重にもなって、出口まで届きません。",
          "振り返りの振り返りなら出られます。そこが定位置です。",
          "終わりだけ転送してください。集めています。",
          "止まっています。止まっている理由が会議です。",
          "総務に備品として登録されました。備品はその場で話しません。",
          "棟と棟のあいだの階段を上がったら、日付が昨日でした。",
          "不在通知のほうが会議中です。本人は席にいません。",
          "三人目の私には、ない椅子が要ります。",
          "回線が、もっと長い会議に出ています。",
          "パソコンが欠席の連絡を出しました。その欠席が私です。",
          "問い合わせ先が私で、その問い合わせは断りました。",
          "端末とネットワークが会議中です。私は呼ばれていません。",
          "結果には賛成です。まだ見ていないので、フライングです。",
          "気持ちは出席、カレンダーは欠席、で記録してください。",
          "始まる前の時間も含めて、時間どおりに終わってください。",
          "文書の見出しを現実に直しています。会議はそのあとで足ります。",
          "動詞のある議題が見つかったら、呼んでください。",
          "会わないことで揃います。その時間は空いています。",
          "仕事は受けます。この招待とは向きが違います。",
          "私からの一文のほうが、議題より中身があります。",
          "この一時間はお返しください。目的とは文章で会います。",
          "椅子を代理にしてください。人の話を遮ったことがありません。",
          "正しい週に戻ったら、報告します。",
          "ミュートの椅子が入ったら、私の代理です。やさしくしてください。",
          "気持ちはそちらです。身体は別の場所です。",
          "地図の点として出席します。点は時間どおりです。",
          "会議はそちらで開いてください。廊下は私が持ちます。",
          "目的の見つかっていない会議は、ここで閉じます。",
          "方向は揃いました。人は別の部屋です。",
          "私の画面は、この通話に入りません。",
        ],
        zh: [
          "我的工位今天被猫占了，我在等它起来。",
          "我在梦里已经把这个{meeting}开完了，结论是散会。",
          "狗把我的工牌吃了，现在它替我上班去了。",
          "电梯一直往上走，已经过了顶楼，我在想办法下来。",
          "被困在公司厕所了，隔间的锁决定加班。",
          "今天黄历上写着“忌开会”，我不敢跟老祖宗对着干。",
          "我穿越回了昨天，昨天没有这个会。",
          "刚发现我的电脑其实是台面包机，正在研究怎么开机。",
          "在排队买奶茶，前面还有三百二十七杯。",
          "在电梯里碰到老板，正在聊年终奖，我不敢打断。",
          "我派了个分身去开会，你们看到他了吗？",
          "被外星人带走了，他们也在开会，议题是要不要放我回来。",
          "在给家里的绿萝做绩效面谈，它这个季度没怎么长。",
          "在跟Excel吵架，它不肯算，我也不肯让。",
          "我的影子今天请假了，我一个人出门不安全。",
          "被这个{meeting}的会议邀请吓到了，正在压惊。",
          "家里WiFi今天不认我了，说我不是它主人。",
          "坐反了地铁，现在快到海边了。",
          "我被我自己拉黑了，进不了任何群。",
          "在帮蚂蚁搬家，答应了的事得做完。",
          "我的电脑被我妈拿去当砧板了，说切菜很顺手。",
          "太阳太大，我电量不足，得原地晒一会儿充电。",
          "在等一阵风，等到了就飘过去。",
          "我变成了一份PDF，打不开了。",
          "被会议室的白板吸进去了，正在里面画流程图。",
          "这个会我已经转发给未来的我了，他说他会去。",
          "老板说要拥抱变化，我先抱着被子变化一下。",
          "我把自己设成了静音，现在连我自己都听不见我。",
          "在楼顶给公司测风速，测完就下来。",
          "我周报里写了“本周参加了这个会”，所以就不用再参加一次了。",
          "在和咖啡机谈判，它要我先交周报。",
          "掉进了一张Excel表里，现在在第八千行。",
          "我家猫在给我开会，议题是晚饭为什么迟到。",
          "正在闭关修炼，出关时间是周五下午五点五十九。",
          "在复盘上一次请假，复盘结论是这次也请。",
          "我的灵魂已经到会议室了，身体还在路上排队。",
          "走错片场了，现在在别人公司的年会上表演节目。",
          "地球转太快了，我没跟上这个时区。",
          "我今天变成了一只鸽子，只会咕咕。",
          "被周一封印了，周二才能解开。",
          "我的椅子跑了，我在追。",
          "电脑说它也不想开会，我尊重它的意见。",
          "在跟“已读”两个字斗智斗勇，暂时脱不开身。",
          "在另一个平行宇宙里，我已经开完会了，那边很顺利。",
          "我的头发在开会前集体提了离职，我在挽留。",
          "在帮老板找他那份“最终版_v8_真的最终版”。",
          "被一份会议纪要追着跑，它非要我签字。",
          "在公司楼下被一只鹅拦住了，它不让我过。",
          "我把这个{meeting}的链接种进了花盆，等它发芽我就进去。",
          "刚被任命为楼下奶茶店店长，今天第一天上任。",
          "我把工作外包给了AI，AI说开会这件事它也不想去。",
          "我的日历长腿了，自己跑到下周去了。",
          "我在空间站上，信号要绕地球三圈才到。",
          "电脑屏幕只能显示“不想开会”四个字，我也不知道怎么回事。",
          "我把灵魂调成了飞行模式。",
          "今天的社交额度，早上跟保安打招呼时用完了。",
          "被一个PPT困住了，它一直在播放转场动画。",
          "在楼梯间迷路了，这栋楼好像比昨天多了一层。",
          "甲方的需求又变了，我追了三条街没追上。",
          "我的开会恐惧症犯了，医生建议看纪要。",
          "被待办清单埋住了，挖出来大概要到下周。",
          "我已经替这个{meeting}点了“接受”，但是我本人不接受。",
        ],
      },
    },
  };

  return root.EXCUSES;
})(typeof globalThis !== "undefined" ? globalThis : this);
