/* Complete excuses. One or two sentences. {meeting} is the only slot. */
var EXCUSES = (function (root) {
  "use strict";

  root.EXCUSES = {
    meetings: [
      { id: "standup", minutes: 15, label: { en: "standup", ja: "朝会", zh: "站会" } },
      { id: "allhands", minutes: 60, label: { en: "all-hands", ja: "全体会議", zh: "全员大会" } },
      { id: "oneonone", minutes: 30, label: { en: "1:1", ja: "1on1", zh: "1对1" } },
      { id: "sync", minutes: 15, label: { en: "quick sync", ja: "すり合わせ", zh: "临时对齐会" } },
      { id: "client", minutes: 45, label: { en: "client call", ja: "お客様との打ち合わせ", zh: "客户会议" } },
    ],
    tones: ["plausible", "suspicious", "absurd"],
    audiences: ["any", "boss", "team", "client"],
    lines: {
      plausible: {
        en: [
          "The meeting before the {meeting} is still going. I'll read the notes when it actually ends.",
          "A hold I put on my own calendar is sitting on this hour. It will not move.",
          "Two invites want this hour, and I already answered the earlier one.",
          "If I leave the call I'm in, both conversations get worse.",
          "Something I promised to finish before this slot is still on the screen.",
          "I'm in the other building. By the time I arrive, the useful part will be over.",
          "My badge opens every door except the one for the {meeting}.",
          "This laptop is installing an update it described as quick. It was optimistic.",
          "The headset is in a room I can see and cannot enter.",
          "The agenda still says TBD, so I'm treating the {meeting} as done.",
          "Everything on the invite would get there sooner as a message.",
          "The {meeting} is marked optional. I'm taking the option.",
          "This slot was going to borrow time from lunch. Lunch is keeping it.",
          "A thread marked urgent opened a few minutes ago, and it believes itself.",
          "The review that started late has not heard that it should end.",
          "Transit is late. I can send the follow-up, not attend the hour.",
          "I stepped out for one document. The document became a corridor.",
          "The block before this one changed its name instead of ending.",
          "I can put the point in writing. I can't be in two rooms.",
          "The camera stopped this morning. A note will be clearer than a black tile.",
          "Audio from my side would be a guess. The {meeting} doesn't need one.",
          "I looked for a decision that needs me live. There isn't one.",
          "I'll be free when the earlier call admits it's over. That isn't a time on the clock.",
          "I'm on the way in, and the way in has the rest of this hour.",
          "I have to sign for something in this exact window. It will not wait.",
          "An earlier commitment is already on this slot. It got here first.",
          "Last time's notes cover this. I'll comment there.",
          "The hours on either side are full. This one didn't get a chair.",
          "The room changed. I'm still walking to the old one.",
          "The doc I said I'd read before we meet is still unread. The doc wins.",
          "This is the only gap I have to send the note I already owe.",
          "The {meeting} overlaps a call I can't drop. I'll take the outcome instead.",
          "I put a focus block here on purpose. It is doing the job.",
          "The earlier meeting has the only headset that works.",
          "I checked the calendar twice. The conflict is still the conflict.",
          "I can make the next one. This one belongs to the meeting before it.",
          "Someone asked for this hour first, and I already said yes.",
          "The train is between stations. The update can leave from here, and I can't.",
          "An appointment I can't move landed on the {meeting}.",
          "The prep isn't finished. I'd rather finish it than show up without it.",
          "I'm covering a desk through the top of the hour. The desk doesn't dial in.",
          "A meeting that was supposed to be short is still here at the start of the {meeting}.",
          "I can do this in writing. The live version doesn't have a job for me.",
          "My part is three lines. The thread fits them better than the room does.",
          "I already sent the update this meeting was going to collect.",
          "The overlap is as long as the {meeting}. There is no remainder.",
          "I'm in the wrong building for a room on this floor.",
          "The badge line downstairs is using up the part of me that arrives on time.",
          "A note I said I'd send first is still unsent. If I join, that note is late too.",
          "Another thread is due at the same time, and that one has a deadline.",
          "I'll read the transcript. The transcript is the version with an ending.",
          "The previous host is still sharing a screen, and I'm still on that calendar.",
          "A one-off I can't reschedule took the hour.",
          "Moving the {meeting} would only move the overlap. I'll take the notes.",
          "I'm on a pickup in this window. I'll read the decisions after.",
          "The invite has no owner and no outcome. I'll wait for the one that does.",
          "I can do the work, or I can attend the {meeting}. The work does not fit in the margin.",
          "A call with a stakeholder moved onto this slot and can't shift. I'll report back.",
          "I'm already late to the meeting I'm in. I won't be early to the next.",
          "The only laptop that's on is mid-update. I'll write when it allows it.",
          "This hour is tentative on one invite and firm on the other. The firm one wins.",
          "The overrun from the last meeting runs straight into the {meeting}.",
        ],
        ja: [
          "前の会議が押していて、{meeting}には間に合いそうにありません。",
          "電車が遅延していて、まだ途中の駅で止まっています。",
          "大雨で駅に入場規制がかかっていて、ホームにたどり着けていません。",
          "乗っているバスが渋滞にはまっていて、到着の時間が読めません。",
          "PCが急にフリーズしてしまい、再起動しても立ち上がりません。",
          "PCの強制アップデートが始まってしまい、終わるまで何もできない状態です。",
          "自宅のWi-Fiが不安定で、つないでもすぐに切れてしまいます。",
          "スマホのキャリアで通信障害が起きていて、テザリングもつながりません。",
          "VPNにつながらず、社内のツールが何も開けません。",
          "パスワードの有効期限が切れて、アカウントにロックがかかってしまいました。",
          "二段階認証用のスマホを家に忘れてしまい、ログインできません。",
          "会議ツールにサインインしようとするとエラーが出て、入れない状態です。",
          "ヘッドセットが壊れてしまい、マイクが使えません。",
          "カメラが急に映らなくなってしまい、今原因を調べているところです。",
          "回線が重くて画面が固まってしまうので、今回は音声だけでも厳しそうです。",
          "朝から少し熱っぽいので、今日は午前休をいただいています。",
          "体調がすぐれないため、病院に寄ってから向かいます。",
          "頭痛がひどいので、薬が効くまで少し休ませてください。",
          "熱はないのですが、喉をやられて声がほとんど出ません。",
          "昼に食べたものに当たったようで、今日はこのまま早退させてください。",
          "歯の詰め物が取れてしまったので、歯医者に行ってきます。",
          "前から予約していた通院の時間と重なってしまいました。",
          "今日は健康診断で、まだ採血の順番待ちをしています。",
          "家族の体調が悪く、病院に付き添っています。",
          "宅配の再配達がちょうどこの時間帯で、家を空けられません。",
          "給湯器の修理業者さんが来ていて、立ち会いが必要です。",
          "マンションの停電でネットが落ちていて、復旧を待っています。",
          "役所の窓口に来ているのですが、順番待ちが思ったより長いです。",
          "実家から親が出てきていて、駅まで迎えに行く約束をしています。",
          "この日は以前から有休をいただいています。",
          "急ぎの対応が入ってしまい、今手が離せません。",
          "今日締め切りの作業がまだ終わっていないので、そちらを優先させてください。",
          "急に別件で呼ばれてしまい、まだ戻れていません。",
          "受付から来客の連絡があり、対応に出ています。",
          "この時間は別の打ち合わせが先に入っていて、{meeting}と重なってしまいました。",
          "終日の社内研修に入っていて、この時間は抜けられません。",
          "外出先から戻る途中で、{meeting}の時間には戻れそうにありません。",
          "移動中で、この時間はちょうど新幹線の中です。",
          "外出先で電波が悪く、通話が途切れ途切れになってしまいます。",
          "スマホの充電が切れそうなのですが、充電器を会社に置いてきてしまいました。",
          "PCを修理に出していて、代わりのPCの設定がまだ終わっていません。",
          "前回の宿題がまだ終わっていないので、出ても報告できることがありません。",
          "議題の件は先週チャットで共有したとおりで、その後変わりはありません。",
          "{meeting}は任意参加とのことなので、今回は議事録で確認させてください。",
          "私の担当分はチャットに書いておきますので、質問はそちらにお願いします。",
          "ちょうど別フロアにいて、今から移動しても間に合いません。",
          "この時間はカレンダーで前からブロックしていたのですが、見えていなかったかもしれません。",
          "新しく入った方に業務を説明する時間と重なっています。",
          "腰を痛めてしまい、長時間座っていられない状態です。",
          "社外から急ぎの問い合わせが入り、今対応しています。",
          "近所で工事をしていて、マイクが工事の音を拾ってしまいます。",
          "寝違えて首が回らず、画面を見るのもつらい状態です。",
          "コンタクトを落としてしまい、画面がほとんど見えていません。",
          "評価面談がちょうどこの時間に入っていて、ずらせませんでした。",
          "ビルの避難訓練が始まってしまい、今は階段で外に出ているところです。",
          "エレベーターが点検中で、上の階まで階段で向かっています。",
          "打ち合わせ用の資料を家に忘れてしまい、取りに戻っています。",
          "先方との電話が長引いていて、まだ切れそうにありません。",
          "社員証を家に忘れてしまい、ビルに入れずにいます。",
          "雨で服がびしょ濡れになってしまったので、着替えてから向かいます。",
          "ちょうどこの時間に、大事な電話がかかってくることになっています。",
          "花粉症がひどく、くしゃみが止まらなくて話せる状態ではありません。",
        ],
        zh: [
          "上一个会拖堂了，还没散，这个{meeting}我赶不上了。",
          "刚被拉进一个线上问题排查，暂时走不开。",
          "客户临时要一版材料，下班前必须交。",
          "这个时间我之前约了别的会，撞了。",
          "电脑在强制更新，进度条才走到一半。",
          "我在外面跑客户，路上信号不太好。",
          "孩子学校临时叫家长，我得过去一趟。",
          "今天有点发烧，请了半天假在家休息。",
          "地铁故障停在半路了，赶不回来。",
          "耳机坏了，麦克风也没声音，进会也说不了话。",
          "手上有个版本今天必须上线，我在盯发布。",
          "这个议题我上周已经在群里同步过了，结论没变。",
          "今天去医院复查，号是早就挂好的，改不了。",
          "我在另一栋楼的会议室，走过去要十几分钟。",
          "领导临时叫我过去对个事。",
          "临时被叫去帮忙接待一位来访的客户，走不开。",
          "今天在外地出差，这个点在高铁上。",
          "有个快递必须本人签收，我在楼下等着。",
          "网断了，手机热点也连不上。",
          "这个会我不是必须参加的，我看纪要就行。",
          "我那部分直接写成文档发群里，大家有问题在评论里提。",
          "下午约了候选人面试，时间撞了。",
          "家里水管漏了，物业师傅马上上门。",
          "刚接到一个紧急工单，在处理。",
          "我在陪客户吃饭，不方便走开。",
          "这个时间段约了供应商对账。",
          "今天调休，人不在公司。",
          "明早要交的方案还差一半，我先赶这个。",
          "今天限号，打不到车，还在路上。",
          "这个{meeting}和我的年假撞了，假上周就批了。",
          "在开另一个项目的评审，暂时出不来。",
          "线上有个报警，我得先看一下。",
          "这周在支援隔壁组，他们上午都排满了。",
          "牙疼，约了下午看牙医。",
          "老家来人了，我去车站接一下。",
          "这个议题我参与得不多，有需要我配合的会后跟我说。",
          "在给新同事做交接，约好的时间不好改。",
          "我在客户现场做部署，一时走不开。",
          "今天上午体检，还在空腹排队。",
          "这个点有个培训考试，缺考还得补。",
          "上午请假去办证件，窗口排队还没轮到我。",
          "领导让我今天把预算表做完，我先弄这个。",
          "日历上这个时间我早就标了忙，可能大家没看到。",
          "我在飞机上，落地再看消息。",
          "吃坏肚子了，今天状态不行，请半天假。",
          "有份合同今天必须盖章寄出，我在跑流程。",
          "今晚系统切换，我得在机房守着。",
          "这周我值班，这个点正好轮到我。",
          "会议软件一直登不上，提示账号异常。",
          "电脑刚蓝屏了，等它重启完，会估计也开完了。",
          "我这边网太卡，进会也是一卡一卡的，不如会后看纪要。",
          "上次会的待办我还没做完，进会也没有新进展可讲。",
          "刚收到客户投诉，得先打电话安抚一下。",
          "家里老人不舒服，我陪着去趟医院。",
          "今天搬工位，电脑还在箱子里没接上。",
          "在做季度复盘材料，明天一早要给领导看。",
          "这个时间我在开车，进会也只能听，不方便说话。",
          "小区停电检修，家里网断了。",
          "在和法务对合同条款，对完才能走。",
          "手机快没电了，充电器落在公司了。",
          "周报系统中午十二点就锁了，我得先交。",
          "这个{meeting}和一个改不了的外部会议撞了，结论麻烦会后发我一下。",
        ],
      },
      suspicious: {
        en: [
          "My calendar double-booked me with myself. I'm in the other one.",
          "I'm already in a meeting about whether the {meeting} should happen.",
          "The invite lists two times. I stayed with the one I saw first.",
          "The previous meeting ended on the calendar and nowhere else.",
          "A five-minute overlap has been five minutes for a while now.",
          "I stopped for one hallway question. It formed a quorum.",
          "Both rooms believe I am in the other one.",
          "Someone accepted the {meeting} for me. They are busy, and so am I.",
          "The room number changed while I was walking to the old one.",
          "I'm badged into the building and not into the {meeting}.",
          "The agenda is the title, repeated. I'm treating that as the whole meeting.",
          "I've been to this meeting. Only the title is new.",
          "The only decision on the invite is whether to hold the {meeting}.",
          "The laptop is awake. The part that joins meetings is asleep.",
          "The headphones are still paired to last week.",
          "I would explain the conflict, but the explanation is booked too.",
          "The calendar settled this without calling a meeting. I'm following its example.",
          "I have been about to join since the invite was still on time.",
          "I can see the meeting room. The meeting room cannot see a reason to open.",
          "Most of the invite is optional. That already feels like an answer.",
          "Send the outcome. An outcome is the only thing I can attend twice.",
          "The loading spinner has perfect attendance. I don't.",
          "I looked through the invite for a verb. I found the name of a meeting.",
          "A copy of this hour is already in progress. I'm in that copy.",
          "The invite moved while I was reading it. I stayed with the old one.",
          "My microphone declined on my behalf.",
          "I'm waiting outside my own desk. The door has not agreed.",
          "The map and the building disagree. I'm with the hallway.",
          "Sound is working for everyone who isn't me.",
          "My remark is three words. It does not need a room.",
          "If I join, you get the version of me that is still on the other call.",
          "The earlier hold has the better claim. I didn't write the rule, but I'm keeping it.",
          "I nodded. The camera decided not to see it.",
          "I'll write the opinion I would have said into the notes.",
          "The other hold doesn't know this invite, and it was here first.",
          "Joining would add a second login to a meeting that already has me.",
          "This meeting needs someone who is only in this meeting.",
          "The update can attend. It says it is almost done.",
          "I refuse to be the frozen face in the corner.",
          "The message already contains the meeting. The meeting does not.",
          "I'm early for a room that isn't on this floor.",
          "Transit gave me a delay and called it a seat.",
          "I'll take the hallway version. It's the short one.",
          "Count me out of the room and in on the notes.",
          "The previous meeting is still introducing itself.",
          "I gave the overlap five more minutes. It accepted them.",
          "My location is approximate. My absence is exact.",
          "The laptop is in a meeting of its own.",
          "I can send a version that loads. This camera can't.",
          "Don't wait on a camera that is still showing this morning.",
          "The only place I still have audio is the thread, so I'll answer there.",
          "The {meeting} is mandatory in the air and optional on the invite. I'm outside.",
          "I was optional last time. I'm keeping the streak.",
          "The earlier block will not give up the chair.",
          "Both bookings have somewhere to be next.",
          "I'm still in the preamble of a meeting that forgot its title.",
          "Please send the sentence this hour was going to turn into.",
          "I'll take the content. I'm declining the gathering.",
          "I have one question, which is why this is live.",
          "I'll edit the doc. That is the {meeting}, without the {meeting}.",
          "If this can be a message, I'll meet you in the message.",
          "The chair is closer than I am, and it doesn't have to walk.",
          "I'm one restart away from being useful, and I'm not taking it.",
          "The other meeting can't find me either. You can start.",
        ],
        ja: [
          "急にネットが不安定になりました。なぜか私のPCだけです。",
          "会議のリンクを押してから、ずっと読み込み中です。もう三十分になります。",
          "野暮用ができました。内容はこれから考えます。",
          "{meeting}は来週だと思い込んでいて、別の予定を入れてしまいました。",
          "家のWi-Fiが落ちました。なぜか動画だけは見られます。",
          "宅配便を受け取りに下りたのですが、荷物が多くて一時間ほどかかりそうです。",
          "カレンダーには何も入っていなかったので、カレンダーを信じることにしました。",
          "前の会議でしゃべりすぎて、声が枯れてしまいました。",
          "PCの更新が始まりました。今日はこれで三回目です。",
          "外にいて周りがうるさいので、聞き専でも厳しそうです。",
          "大事な用事を思い出しました。何だったかを今思い出しているところです。",
          "もう向かっています。自宅の方向にですが。",
          "招待メールが迷惑メールフォルダに入っていて、今気づきました。",
          "急ぎの依頼が来ています。どのくらい急ぎかは聞いていません。",
          "カメラとマイクが同時に壊れました。どちらも今日です。",
          "別の会議と重なっています。そちらの主催も私です。",
          "お昼のあとなので、頭がまだ起動中です。",
          "大事な電話を待っています。まだかかってきませんが、いつかかってくるか分かりません。",
          "停電しています。うちだけです。",
          "ワイヤレスイヤホンが隣の家のテレビにつながってしまい、対応中です。",
          "急ぎの資料を作っています。ファイル名はまだ決まっていません。",
          "猫がキーボードの上で寝ていて、起こすと怒られます。",
          "チャットのステータスが「離席中」から戻りません。私もまだ戻れていません。",
          "今日は仏滅なので、大事な会議は避けておきたいです。",
          "新しく入った方に社内を案内しています。主に社食です。",
          "電車で寝過ごして、終点まで来てしまいました。",
          "エレベーターの中で電波が切れました。今もエレベーターの中です。",
          "生活リズムを整えている最中で、この時間は寝ている予定になっています。",
          "出前が隣のマンションに届いてしまったので、取りに行ってきます。",
          "準備は頭の中では完璧なので、外に出すまで少し時間をください。",
          "{meeting}は前回出たので、今回もだいたい同じ内容だと思っています。",
          "先ほど上司に「無理しなくていいよ」と言われたので、そういう意味だと受け取りました。",
          "プロジェクターにつながらないので、私も今日はつながらないことにしました。",
          "エアコンの修理の人が来ていて、見守っています。もう一時間見守っています。",
          "新幹線がトンネル続きで、ずっと圏外です。",
          "今日の服がカメラ向きではありません。",
          "Excelが応答していません。待っているあいだ、私も応答できません。",
          "健康診断の前日なので、今日は無理をしないようにしています。",
          "社内チャットで議論が白熱していて、見届ける必要があります。",
          "PCの充電が切れました。充電器は同僚に貸していて、その同僚は今日休みです。",
          "目覚ましを午後にセットしていて、今起きました。",
          "配達員さんから「あと三分で着きます」と連絡があってから、四十分経ちました。",
          "部長に出す大事な資料を作っています。部長はまだこの件を知りません。",
          "{meeting}のリンクを開いたら、去年の会議につながりました。",
          "電波の届かない場所にいて、このメッセージも順番待ちで送られています。",
          "冷房が効きすぎていて、外で体を温めています。",
          "プリンターが紙詰まりを起こし、私も詰まっています。",
          "今日の午前中はステータスを「応答不可」にしてあるので、その設定を尊重します。",
          "データを確認しています。量が多く、{meeting}が終わるころまでかかりそうです。",
          "歯医者に空きが出たと連絡がありました。歯はまだ痛くないのですが、せっかくなので。",
          "母からビデオ通話がかかってきて、切ると心配されます。",
          "会議室に着きました。たぶん違う会議室です。",
          "{meeting}は、私とはあまり関係がない気がしています。",
          "コーヒーを淹れたばかりなので、冷めるまで待ちます。",
          "根回しがまだ終わっていないので、今出ると話がまとまりません。",
          "今日は議事録の当番が回ってきそうな予感がするので、様子を見ます。",
          "課長にハンコをもらうため、席の前で待っています。課長はまだ戻りません。",
          "昨日の飲み会が、まだ体に残っています。",
          "傘を持っていないので、雨がやむのを待っています。",
          "家を出ようとしたら鍵が見当たらず、まだ部屋の中を探しています。",
          "コンプラ研修のeラーニングが今日締め切りで、まだ一問目です。",
          "体調は悪くないのですが、良くもないので、念のため休みます。",
        ],
        zh: [
          "网突然不太好，只有我这台电脑不好。",
          "进会一直在转圈，已经转了半小时了。",
          "有点事，具体什么事，等我想好了再说。",
          "会议链接点不开，我就没再点了。",
          "我以为这个{meeting}是下周的，今天已经约了别的。",
          "家里WiFi坏了，只有外卖软件还能用。",
          "我在楼下取快递，快递有点多，大概要一个小时。",
          "我日历上今天没有会，我选择相信日历。",
          "刚开完一个会，嗓子说哑了，得歇一歇。",
          "电脑在更新，这已经是今天第三次了。",
          "我在外面，旁边太吵了，听不清，就先不进了。",
          "突然想起一件很重要的事，正在想是什么事。",
          "我已经在路上了，往家的方向。",
          "腰闪了，坐着疼，站着疼，开会更疼。",
          "会议邀请掉进了垃圾邮件，我也是刚翻到。",
          "手上有个紧急需求，客户说很急，具体多急他也没说。",
          "摄像头坏了，麦克风也坏了，刚好都是今天。",
          "我在开另一个会，那个会也是我自己约的。",
          "刚吃完午饭，大脑还在加载。",
          "这个{meeting}的议题，我已经在心里对齐过了。",
          "在等一个很重要的电话，它还没打来，但随时会打来。",
          "停电了，只停了我家这一户。",
          "蓝牙耳机连到了邻居家的电视上，正在处理。",
          "有个文档要赶，文档名字还没想好。",
          "在体检，排的人有点多，可能要排到下班。",
          "猫把键盘踩坏了，现在只剩退出键能用。",
          "我钉钉一直显示离线，我自己也觉得我离线了。",
          "今天水逆，不宜开会。",
          "在带新人熟悉业务，主要是熟悉食堂。",
          "车停的地方要被贴条了，我下去挪个车，可能挪得有点远。",
          "刚才在电梯里断了信号，现在还在电梯里。",
          "这周在调作息，按计划这个点我在睡觉。",
          "外卖送错小区了，我得去隔壁小区拿。",
          "我准备得很充分，都准备在脑子里了，还需要点时间整理。",
          "这个会上次参加过了，我感觉大家说的应该差不多。",
          "刚跟领导汇报完，领导说我可以不用来了。我理解是这个意思。",
          "投影我连不上，所以人也决定先不连了。",
          "家里来了修空调的师傅，我得在旁边看着。已经看了很久了。",
          "在高铁上，这一路隧道有点多，全程都是隧道。",
          "今天穿的衣服不太适合开摄像头。",
          "在排查一个bug，bug说再给它一个小时。",
          "手上有件急事，急的程度大概跟这个会差不多。",
          "被拉进一个群，群里正在吵架，我得在场。",
          "电脑没电了，充电器被同事借走了，同事今天休假。",
          "闹钟设成了下午，刚醒。",
          "外卖骑手说三分钟到，已经说了四十分钟了。",
          "在给领导写一份很重要的材料，领导还不知道这件事。",
          "这个{meeting}的链接我点了，跳出来的是去年的会。",
          "我在一个没信号的地方，这条消息是排队发出来的。",
          "空调太冷了，我在楼下晒太阳回温。",
          "打印机卡纸了，我也卡住了。",
          "我今天上午的状态是“请勿打扰”，我得尊重它。",
          "下午有个面试。是我面别人，应该是。",
          "在核对数据，数据有点多，可能要核到会议结束。",
          "牙医说今天有空位，我牙还没疼，但机会难得。",
          "在帮行政搬水，一桶接一桶。",
          "我已经在会议室了，但好像不是这间。",
          "我妈突然打视频过来，挂了她会问我是不是在忙。",
          "楼下有个快递必须本人去拿，而且必须是现在。",
          "在开车，导航让我一直往前开。",
          "这个会跟我关系不大，我是这么感觉的。",
          "刚给自己倒了杯咖啡，等它凉了再说。",
        ],
      },
      absurd: {
        en: [
          "My calendar double-booked me with myself, and the other me already accepted. I'm in the other one.",
          "The {meeting} accepted itself. I was not consulted.",
          "A previous version of me is already on the invite. Their notes are better.",
          "This hour belongs to a recurring event called Do Not. It has never missed.",
          "I tried to decline. The decline is waiting for approval.",
          "The meeting before this one is still introducing the meeting before that.",
          "A short question from this morning appointed a chair and a note-taker.",
          "I would leave the previous meeting, but it hasn't admitted I'm here, so I can't exit.",
          "The {meeting} is in a room that exists only on the invite.",
          "My chair is attending. I was not on the delivery list.",
          "The elevator accepted the meeting and left the passengers behind.",
          "My microphone only speaks in calendar notifications.",
          "The laptop joined the {meeting} without me. It is doing fine.",
          "The camera will not cross the loading bar.",
          "The agenda is a link to the agenda, and the link is this {meeting}.",
          "I went to the pre-meeting. It was the pre-meeting for another pre-meeting.",
          "The {meeting} was there to keep the calendar from looking empty. The calendar looks fine.",
          "Every item says align. We are aligned, so the meeting can stay home.",
          "I brought a decision. The agenda told me to leave it outside.",
          "This meeting fits in one sentence. The sentence is no.",
          "I shortened the agenda, and the short version called in absent.",
          "Time is attending. I'm the optional one.",
          "The overlap contains another overlap. I'm in the inner one.",
          "I sent my regrets. The meeting replied with an agenda.",
          "A blank with my name will attend. It has opinions and no microphone.",
          "Count me present in the attachments.",
          "I'm sending the yes in advance. That's the only way I can attend.",
          "If I appear, that is the other me, and it doesn't get a vote.",
          "I'll haunt the document, not the call.",
          "A more presentable copy of me will write later. This one is fully booked.",
          "You will get the work. The work is not double-booked.",
          "Please remove the copy of me that can still see a clock.",
          "The meetings are nested too deep. I can't reach the exit.",
          "I can attend the recap of the recap. That's my assigned seat.",
          "Forward only the ending. I collect those.",
          "My status is blocked. The blocker is a meeting.",
          "Facilities registered me as furniture. Furniture doesn't speak live.",
          "I took the stairs between buildings and came out yesterday.",
          "My out-of-office reply is in a meeting. I am not at my desk.",
          "A third copy of me would need a chair we don't have.",
          "My bandwidth is attending a longer meeting.",
          "The laptop sent a decline. I am that decline.",
          "Technical support is me, and I closed the ticket.",
          "The laptop is meeting with the network. I was not invited.",
          "I support the outcome. I haven't been shown one, so this is early.",
          "Please mark me present in spirit and absent on the calendar.",
          "Please end on time, including the time before it starts.",
          "I'm in the document, making the headings match reality. The meeting can wait.",
          "If anyone finds an agenda item with a verb, call me.",
          "We can be aligned by not meeting. I'm free for that.",
          "I'll take the work. This invitation faces the other way.",
          "One sentence from me will contain more than the agenda does.",
          "Please take the hour back. The purpose and I will meet in writing.",
          "Let the chair represent me. It has never talked over anyone.",
          "I'll report once I get back to the correct week.",
          "If a muted chair joins, that's my delegate. Be polite to it.",
          "I'm there in intention. The rest of me is elsewhere.",
          "I'll attend as a dot on the map. The dot is on time.",
          "You hold the meeting. I'll hold the hallway.",
          "This meeting has not found a purpose. I'm closing it here.",
          "The direction is settled. The person is in another room.",
          "My tile has declined to enter the call.",
        ],
        ja: [
          "夢の中で{meeting}はもう終わりました。結論は解散でした。",
          "社員証を犬に食べられました。今日は犬が代わりに出社しています。",
          "エレベーターが屋上を通り過ぎて、まだ上がり続けています。",
          "トイレの個室の鍵が残業を始めてしまい、出られません。",
          "昨日にタイムスリップしてしまいました。昨日は{meeting}がない日です。",
          "PCだと思っていたものがトースターでした。今、電源の入れ方を調べています。",
          "コンビニのレジに並んでいます。前にあと三百人います。",
          "分身を会議に送りました。そちらに着いていますか。",
          "宇宙人に連れ去られました。向こうも会議中で、議題は私を帰すかどうかです。",
          "観葉植物と評価面談をしています。今期はあまり伸びていません。",
          "Excelと口論中です。向こうが計算してくれないので、こちらも引けません。",
          "影が有休を取ったので、一人で外に出るのは危ないです。",
          "家のWi-Fiに「あなたは誰ですか」と聞かれていて、答えに詰まっています。",
          "自分で自分をブロックしてしまい、どのチャンネルにも入れません。",
          "アリの引っ越しを手伝う約束をしてしまいました。約束は守る主義です。",
          "私の充電が切れたので、日なたで充電しています。",
          "私がPDFになってしまい、開けなくなりました。",
          "会議室のホワイトボードに吸い込まれて、中で図を描いています。",
          "この会議は未来の私に転送しました。行くと言っています。",
          "自分をミュートにしたら、自分の声も聞こえなくなりました。",
          "週報に「{meeting}に出席」と書いてしまったので、もう出たことになっています。",
          "コーヒーマシンと交渉中です。先に週報を出せと言われています。",
          "スプレッドシートの8000行目に落ちてしまい、まだ上がってこられません。",
          "猫が会議を開いていて、議題は晩ごはんが遅れた件です。",
          "山ごもりに入りました。下山は金曜の17時59分です。",
          "魂だけ先に会議室に着いています。体はまだ改札です。",
          "地球の自転が速すぎて、タイムゾーンについていけません。",
          "今日は貝になったので、口が開きません。",
          "月曜日に封印されていて、解けるのは火曜です。",
          "椅子が逃げたので、追いかけています。",
          "PCも会議に出たくないと言っているので、意見を尊重します。",
          "既読をつけるかどうかで、スマホとにらみ合っています。",
          "パラレルワールドの私が出席しました。向こうでは順調だったそうです。",
          "髪の毛が会議の前に一斉に退職届を出したので、引き止めています。",
          "部長の「最終版_v8_本当に最終」を一緒に探しています。",
          "議事録に追いかけられています。ハンコを押せと言われています。",
          "会社の前でカラスに通せんぼされています。目が合ってしまいました。",
          "{meeting}のリンクを植木鉢に植えました。芽が出たら入ります。",
          "下のコンビニの店長に任命されました。今日が初日です。",
          "仕事をAIに任せたら、AIも会議には出たくないそうです。",
          "カレンダーに足が生えて、来週まで逃げていきました。",
          "宇宙ステーションにいるので、電波が地球を三周してから届きます。",
          "画面に「会議に出たくない」としか表示されません。原因は不明です。",
          "魂を機内モードにしました。",
          "今日のコミュ力は、朝の守衛さんへの挨拶で使い切りました。",
          "パワポのアニメーションが終わらず、中に閉じ込められています。",
          "階段で迷いました。ビルが昨日より一階増えています。",
          "先方の要望がまた変わったので、走って追いかけています。まだ追いつきません。",
          "会議アレルギーが出ました。医者には議事録を勧められています。",
          "ToDoリストに埋もれていて、掘り出されるのは来週の見込みです。",
          "{meeting}の「参加」は押しておきました。本人は参加しません。",
          "ハンコを押しすぎて、手がハンコになりました。",
          "満員電車に押し込まれたまま、気づいたら終点の車庫にいました。",
          "根回しをしていたら、根が地球の裏側まで伸びてしまいました。",
          "自販機に話しかけられて、会話が終わりません。",
          "通勤中に異世界に転生しました。こちらで勇者の仕事が入ったので失礼します。",
          "席替えで、私の席が屋上になりました。",
          "名刺を切らしているので、今日の私は誰でもありません。",
          "フリーアドレスが広がりすぎて、今日の席は隣の県になりました。",
          "前の会議がまだ自己紹介をしています。三周目に入りました。",
          "「会議を減らすための会議」が延長になったので、そちらに出ています。",
          "予約システムに、私が会議室として登録されていました。今日は貸し出し中です。",
        ],
        zh: [
          "我的工位今天被猫占了，我在等它起来。",
          "我在梦里已经把这个{meeting}开完了，结论是散会。",
          "狗把我的工牌吃了，现在它替我上班去了。",
          "电梯一直往上走，已经过了顶楼，我在想办法下来。",
          "被困在公司厕所了，隔间的锁决定加班。",
          "今天黄历上写着“忌开会”，我不敢跟老祖宗对着干。",
          "我穿越回了昨天，昨天没有这个会。",
          "刚发现我的电脑其实是台面包机，正在研究怎么开机。",
          "在排队买奶茶，前面还有三百二十七杯。",
          "在电梯里碰到老板，正在聊年终奖，我不敢打断。",
          "我派了个分身去开会，你们看到他了吗？",
          "被外星人带走了，他们也在开会，议题是要不要放我回来。",
          "在给家里的绿萝做绩效面谈，它这个季度没怎么长。",
          "在跟Excel吵架，它不肯算，我也不肯让。",
          "我的影子今天请假了，我一个人出门不安全。",
          "被这个{meeting}的会议邀请吓到了，正在压惊。",
          "家里WiFi今天不认我了，说我不是它主人。",
          "坐反了地铁，现在快到海边了。",
          "我被我自己拉黑了，进不了任何群。",
          "在帮蚂蚁搬家，答应了的事得做完。",
          "我的电脑被我妈拿去当砧板了，说切菜很顺手。",
          "太阳太大，我电量不足，得原地晒一会儿充电。",
          "在等一阵风，等到了就飘过去。",
          "我变成了一份PDF，打不开了。",
          "被会议室的白板吸进去了，正在里面画流程图。",
          "这个会我已经转发给未来的我了，他说他会去。",
          "老板说要拥抱变化，我先抱着被子变化一下。",
          "我把自己设成了静音，现在连我自己都听不见我。",
          "在楼顶给公司测风速，测完就下来。",
          "我周报里写了“本周参加了这个会”，所以就不用再参加一次了。",
          "在和咖啡机谈判，它要我先交周报。",
          "掉进了一张Excel表里，现在在第八千行。",
          "我家猫在给我开会，议题是晚饭为什么迟到。",
          "正在闭关修炼，出关时间是周五下午五点五十九。",
          "在复盘上一次请假，复盘结论是这次也请。",
          "我的灵魂已经到会议室了，身体还在路上排队。",
          "走错片场了，现在在别人公司的年会上表演节目。",
          "地球转太快了，我没跟上这个时区。",
          "我今天变成了一只鸽子，只会咕咕。",
          "被周一封印了，周二才能解开。",
          "我的椅子跑了，我在追。",
          "电脑说它也不想开会，我尊重它的意见。",
          "在跟“已读”两个字斗智斗勇，暂时脱不开身。",
          "在另一个平行宇宙里，我已经开完会了，那边很顺利。",
          "我的头发在开会前集体提了离职，我在挽留。",
          "在帮老板找他那份“最终版_v8_真的最终版”。",
          "被一份会议纪要追着跑，它非要我签字。",
          "在公司楼下被一只鹅拦住了，它不让我过。",
          "我把这个{meeting}的链接种进了花盆，等它发芽我就进去。",
          "刚被任命为楼下奶茶店店长，今天第一天上任。",
          "我把工作外包给了AI，AI说开会这件事它也不想去。",
          "我的日历长腿了，自己跑到下周去了。",
          "我在空间站上，信号要绕地球三圈才到。",
          "电脑屏幕只能显示“不想开会”四个字，我也不知道怎么回事。",
          "我把灵魂调成了飞行模式。",
          "今天的社交额度，早上跟保安打招呼时用完了。",
          "被一个PPT困住了，它一直在播放转场动画。",
          "在楼梯间迷路了，这栋楼好像比昨天多了一层。",
          "甲方的需求又变了，我追了三条街没追上。",
          "我的开会恐惧症犯了，医生建议看纪要。",
          "被待办清单埋住了，挖出来大概要到下周。",
          "我已经替这个{meeting}点了“接受”，但是我本人不接受。",
        ],
      },
    },
  };

  return root.EXCUSES;
})(typeof globalThis !== "undefined" ? globalThis : this);
